### ISSUE TITLE
rotctld rot_caps to reflect underlying rotator functions

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#1035]
Expand dump_state for rotctld to include all the functions too and complete rig_caps capabilities

**Comment by PianetaRadio** [comment]
Hi Mike, please try to address this issue in v.4.5.1

TNX

**Comment by mdblack98** [comment]
Can you explain exactly what's missing?
There are these four items
Get functions: 
Set functions: 
Extra functions:
Can set Func:	N
Can get Func:	N

But not one rotator has any get/set function defined.

**Comment by PianetaRadio** [comment]
I added in my commit south_zero that was missing from dump state.

In my opinion one important info is missing from dump caps:
- rot_type (should reflect the real rotator, not to be the generic ROT_TYPE_OTHER)

To simplify, maybe rot_type could be added in the state structure also.

**Comment by mdblack98** [comment]
Thanks for the patch.

The are no "Can Set and Can Get" functions in any rotor.
Rotors only know movement -- not what we call a "function" in Hamlib.  Functions are generally things you toggle on/off.

**Comment by PianetaRadio** [comment]
Sorry, I will try to explain better: I mean something like "my_rot->caps->park" doesn't work as expected with Net rotator, beacuse doesn't take it from the real rotator caps.

**Comment by mdblack98** [comment]
What rotor needs to have the ROT_TYPE_OTHER changed?  Some items are controllers with no specific direction.  Consder "OTHER" to mean "GENERIC".

**Comment by PianetaRadio** [comment]
Consider for example my application software CatRotator:
- The GUI is responsive to the rotator type, if the rotator is azimuth only, the elevation indicator disappear from the interface.
- If the rotator has park function, the interface use it, otherwise send the rotator in the direction selected by the user in the setup.

And so on, there is a series of features that couldn't be used with the NET rotctl.

**Comment by mdblack98** [comment]
Application doesn't matter.
It has to do with the rotor's capability.   Some rotors are not directional at all...you can hook them up however you want.So you need to allow for OTHER by having the user manually select AZ, EL, or AZ/EL.
rotctl cannot magically figure out how it's hooked up.


 

    On Monday, November 7, 2022 at 12:15:12 PM CST, PianetaRadio ***@***.***> wrote:  
 
 


Consider for example my application software CatRotator:
   
   - The GUI is responsive to the rotator type, if the rotator is azimuth only, the elevation indicator disappear from the interface.
   - If the rotator has park function, the interface use it, otherwise send the rotator in the direction selected by the user in the setup.

And so on, there is a series of features that couldn't be used with the NET rotctl.

**Comment by PianetaRadio** [comment]
For example:

```
Caps dump for model:    1701
Model name:             D azimuth
Mfg name:               Prosistel
Backend version:        20201215.0
Backend copyright:      LGPL
Backend status:         Stable
Rot type:               Azimuth
Port type:              RS-232
Serial speed:           9600..9600 bauds, 8N1
Write delay:            0mS, timeout 3000mS, 3 retries
Post Write delay:       0mS
Status flags: None

Get functions:
Set functions:
Extra functions:
Get level:
Set level:
Extra levels:
Get parameters:
Set parameters:
Extra parameters:
Min Azimuth:            0.00
Max Azimuth:            360.00
Min Elevation:          0.00
Max Elevation:          0.00
Has priv data:          Y
Has Init:               N
Has Cleanup:            N
Has Open:               Y
Has Close:              N
Can set Conf:           N
Can get Conf:           N
Can set Position:       Y
Can get Position:       Y
Can Stop:               Y
Can Park:               N
Can Reset:              N
Can Move:               N
Can get Info:           N
Can get Status:         N
Can set Func:   N
Can get Func:   N
Can set Level:  N
Can get Level:  N
Can set Param:  N
Can get Param:  N
```


The same rotator connected via NET
```
Caps dump for model:    2
Model name:             NET rotctl
Mfg name:               Hamlib
Backend version:        20200528.0
Backend copyright:      LGPL
Backend status:         Stable
Rot type:               Other
Port type:              Network link
Write delay:            0mS, timeout 2000mS, 3 retries
Post Write delay:       0mS
Status flags: None
Get functions:
Set functions:
Extra functions:
Get level:
Set level:
Extra levels:
Get parameters:
Set parameters:
Extra parameters:
Min Azimuth:            0.00
Max Azimuth:            360.00
Min Elevation:          0.00
Max Elevation:          0.00
Has priv data:          N
Has Init:               N
Has Cleanup:            N
Has Open:               Y
Has Close:              Y
Can set Conf:           N
Can get Conf:           N
Can set Position:       Y
Can get Position:       Y
Can Stop:               Y
Can Park:               Y
Can Reset:              Y
Can Move:               Y
Can get Info:           Y
Can get Status:         N
Can set Func:   N
Can get Func:   N
Can set Level:  N
Can get Level:  N
Can set Param:  N
Can get Param:  N
```

As you can check there are some discrepancies.
If I undestand well is not possible to correct this.
