### ISSUE TITLE
icom_rig_open: rig error getting frequency retry=0, err=Invalid parameter with IC-9700

### ISSUE THREAD

**Issue by dl2sba** [Hamlib/Hamlib#1039]
Hello

I failed even at the first step. I'm using HAMLIB 4.4 on GERMAN Windows10 together with an IC-9700.

IC-9700 has FW:

Main 1.31
Sub+Front CPU 1.00

Rig is set up as described here: https://github.com/csete/gpredict/blob/master/doc/notes/ic-9700.txt

I get "icom_rig_open: rig error getting frequency retry=0, err=Invalid parameter" right after start.
I can see the frequency response from the radio - but then rigctl shows errors ...

[rigctld.log](https://github.com/Hamlib/Hamlib/files/8778006/rigctld.log)

Any help is appreciated

//Dietmar

**Comment by dl2sba** [comment]
I got some cm forward ...

This command liine works better:

**rigctl -m 3081 -r COM7 --civaddr 0xA2 -vvvvvvvvvvvvvv**

Now I can query the frequency with **f**. But setting the frequency with **F** ends in 

`Rig command: F`
`Frequency: 433000000`
`set_freq: error = Command rejected by the rig`
`icom.c(1328):icom_set_freq return(-9)`
`rig.c(1952):rig_set_freq return(-9)`
`rigctl_parse.c(2004):rigctl_set_freq return(-9)`

Any ideas?

**Comment by mdblack98** [comment]
The civaddr is redundant -- that's the default.
What version are you running?
rigctl --version
And the debug you show is not the full debug.  You just need 5 v's and then send the debug from that.
Mike W9MDB


 

    On Thursday, May 26, 2022, 08:15:42 AM CDT, Dietmar, DL2SBA ***@***.***> wrote:  
 
 


I got some cm forward ...

This command liine works better:

rigctl -m 3081 -r COM7 --civaddr 0xA2 -vvvvvvvvvvvvvv

Now I can query the frequency with f. But setting the frequency with F ends in

Rig command: F
Frequency: 433000000
set_freq: error = Command rejected by the rig
icom.c(1328):icom_set_freq return(-9)
rig.c(1952):rig_set_freq return(-9)
rigctl_parse.c(2004):rigctl_set_freq return(-9)

Any ideas?

**Comment by dl2sba** [comment]
Tnx Mike

Hi All

I have problems running my IC-9700 (FW 1.31) with gpredict (gpredict-win32-2.3.37 or gpredict-win32-2.2.1) and hamlib (hamlib-w64-4.5~git or 4.4). The different versions show same issues :-/

IC-9700 & gpredict is set according to https://github.com/csete/gpredict/blob/master/doc/notes/ic-9700.txt

This is the command line for rigctld:

`rigctld -m 3081 -r COM7 -s 115200 -T 127.0.0.1 -t 9700 -vvvvv`

When I click the ENGAGE-button the frequencies on the IC9700 flicker a few times, then the ENGAGE-button becomes unselected again.

Sorry for initial confusion!

[rigctld.log](https://github.com/Hamlib/Hamlib/files/8781508/rigctld.log)
 
//Dietmar

**Comment by dl2sba** [comment]
Switching to Hamlib 4.1 gives a working combo.

**Comment by mdblack98** [comment]
Leaving this open as this is still a bug apparently
