### ISSUE TITLE
TS-890S missing Can send Morse

### ISSUE THREAD

**Issue by GeoBaltz** [Hamlib/Hamlib#1043]
Using hamlib 4.4, the Kenwood TS-890S says it can't send Morse.  It looks like it's just missing a couple of lines, as all the other Kenwood rigs I looked into have them.  Is this just an oversight, or is it really broken?

**Comment by mdblack98** [comment]
It's been added

**Comment by GeoBaltz** [comment]
Shouldn't this get a
 `    .wait_morse =  rig_wait_morse,`
also?

**Comment by GeoBaltz** [comment]
Oops, my bad.  Also needs RIG_FUNC_SEND_MORSE added to its capabilities.

**Comment by mdblack98** [comment]
Added.
Mike W9MDB

 

    On Thursday, June 16, 2022, 03:25:53 AM CDT, GeoBaltz ***@***.***> wrote:  
 
 


Oops, my bad. Also needs RIG_FUNC_SEND_MORSE added to its capabilities.
