### ISSUE TITLE
TX-500 with rigctl

### ISSUE THREAD

**Issue by conotto** [Hamlib/Hamlib#1051]
Hi,
I noticed that even though lib support for TX-500 from lab599 was added, rigctl does not list it as supported rig.
Are there any plans to add it ?
I am using latest hamlib 4.4 on linux

Thanks

**Comment by mdblack98** [comment]
What version are you running?  It is listed.rigctl --version
  2050  Lab599                 TX-500                  20220602.0      Stable      RIG_MODEL_LAB599_TX500

 

    On Friday, June 3, 2022, 07:38:34 AM CDT, Otto ***@***.***> wrote:  
 
 


Hi,
I noticed that even though lib support for TX-500 from lab599 was added, rigctl does not list it as supported rig.
Are there any plans to add it ?

Thanks
