### ISSUE TITLE
ID-5100 .serial_handshake

### ISSUE THREAD

**Issue by Kvolt** [Hamlib/Hamlib#1053]
Currently is .serial_handshake = RIG_HANDSHAKE_NONE,
As per Manual, Flow control: Xon/Xoff

**Comment by mdblack98** [comment]
I assume you're using one?  And it working OK with hamlib?

**Comment by Kvolt** [comment]
No Sir, I found the issue while trying to resolve an issue with Direwolf. And I haven't had to time to update the file and test it. I was informed by the program creater that "xon/xoff is unusual. I don't see a way to make direwolf use this method, but each gui app (wsjtx/sstv/js8call) will have a check box for this". So this is a project in process.
