### ISSUE TITLE
ICOM AGC levels need improving

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#1096]
Review all Icom rig AGC levels and see if we can incorporate the default settings for the rigs plus user-specified.
So users should be able to use FAST MEDIUMD SLOW or floating point values to set the AGC time constant.
It would appear that not all AGC mapping is correct.

**Comment by PianetaRadio** [comment]
It will be useful if Icom AGC levels list is accessible via rig->caps like other backend.
At the moment the priv_caps makes they difficult to access by extern code, since it is declared only inside icom.h
