### ISSUE TITLE
FT-736 panel locking

### ISSUE THREAD

**Issue by egislev** [Hamlib/Hamlib#1117]
Hello all.
I found disabled feature in later then 3.3 versions of subj panel locking. In 3.3 feature was : then no clients are connected to rigctld, panel is unlocked and is locked only then TCP/IP client is connected. In 4.4 version panel is locked allways.
This is very usefull feature for this transceiver (because here is no read-back of frequency, as i know) when working with sats.

**Comment by mdblack98** [comment]
New option -R for rigctld will close the rig when no clients are connected
