### ISSUE TITLE
python2 and python3 import Hamlib binding problem 

### ISSUE THREAD

**Issue by muhammetfaik** [Hamlib/Hamlib#1122]
I build hamlib for python2 and python3 but I have problem in both.
python2:
```
 python2
Python 2.7.18 (default, Jul  1 2022, 10:30:50) 
[GCC 11.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Hamlib 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/Hamlib.py", line 15, in <module>
    import _Hamlib
ImportError: dynamic module does not define init function (init_Hamlib)
>>> 
```
python3:
```
python3 
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Hamlib 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: bad magic number in 'Hamlib': b'\x03\xf3\r\n'
>>>  u  22.04 
```
Help Me !!

**Comment by mdblack98** [comment]
Make sure you add the path to the python Hamlib bindinge.g.
ls /usr/local/lib/python3.10/site-packages/_Hamlib.a  _Hamlib.la  Hamlib.py  _Hamlib.so  __pycache__
sys.path.append('/usr/local/lib/python3.10/site-packages')

And is should just beimport HamlibNo underscore.
Mike W9MDB
 

    On Tuesday, September 27, 2022 at 01:40:22 AM CDT, Muhammet Faik ***@***.***> wrote:  
 
 


I build hamlib for python2 and python3 but I have problem in both.
python2:
 python2
Python 2.7.18 (default, Jul  1 2022, 10:30:50) 
[GCC 11.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Hamlib 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/Hamlib.py", line 15, in <module>
    import _Hamlib
ImportError: dynamic module does not define init function (init_Hamlib)
>>> 

python3:
python3 
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Hamlib 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: bad magic number in 'Hamlib': b'\x03\xf3\r\n'
>>>  u  22.04 

Help Me !!
