### ISSUE TITLE
IC-9700 cannot use AGC_OFF

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#1136]
In order to do AGC_OFF on the IC9700/7300 must set the AGC time constant=0 
AGC time constant settings
Command: 1A 04

**Comment by mikaelnousiainen** [comment]
I think this may apply to all Icom SDR rigs like 7300, 705 and 7610.

**Comment by mdblack98** [comment]
This needs to be added to more rigs that have AGC_TIME settings
