### ISSUE TITLE
TS-890S doesn't get CW speed

### ISSUE THREAD

**Issue by GeoBaltz** [Hamlib/Hamlib#1139]
TLF logger won't send CW via HAMLIB_KEYER to a TS-890S - it wants to get/set CW keying speed and fails.

Need to add RIG_LEVEL_KEYSPD to #define TS890_LEVEL_ALL.

**Comment by vk4tux** [comment]
Message ID: ***@***.***>
> Just a note that Universal_HamRadio_Remote_HTML5 hamlib does not seem 
> to support RIGCTLD connection ?

[HAMLIB]
rig_pathname = 192.168.0.19
retry = 5
rig_model = NETRIGCTL
trxautopower = True
rig_rate = 38400


does not operate.


73


Adrian Fewster

**Comment by mdblack98** [comment]
The Universal_HamRadio_Remote_HTML5 problem should be reported to them.  Nothing we can do about it not working.
