### ISSUE TITLE
FT857D VFOa and VFOb not switching correctly

### ISSUE THREAD

**Issue by visseroth** [Hamlib/Hamlib#1145]
FT857D the VFO doesn't match nor sync correctly.
Clicking on VFOa causes a switch to be and sometimes to b and back to a.
Clicking on A/B causes a switch back and fourth too.
The indicator on A or B does not match what's on the radio.

**Comment by mdblack98** [comment]
What application are you using?
Mike W9MDB
    On Thursday, November 10, 2022 at 04:46:53 PM CST, visseroth ***@***.***> wrote:  
 
 


FT857D the VFO doesn't match nor sync correctly.
Clicking on VFOa causes a switch to be and sometimes to b and back to a.
Clicking on A/B causes a switch back and fourth too.
The indicator on A or B does not match what's on the radio.

**Comment by visseroth** [comment]
FLRig 1.4.7

**Comment by mdblack98** [comment]
FLRig does not use Hamlib.
Needs to be reported to https://groups.io/g/winfldigi
Mike W9MDB
