### ISSUE TITLE
/bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by hack-r** [Hamlib/Hamlib#1146]
Not sure why, but `bootstrap` threw 

`/bin/bash^M: bad interpreter: No such file or directory`

for me, so I had to run 

`sed -i -e 's/\r$//' bootstrap`

to make it work. Just FYI.

**Comment by mdblack98** [comment]
Git checkout?  On on what platform?
I just checked and boostrap only has 0xa in it.
0000000    2123    622f    6e69    732f    0a68    230a    5220    6e75          #   !   /   b   i   n   /   s   h  nl  nl   #  sp   R   u   n

Mike W9MDB

 

    On Saturday, November 12, 2022 at 07:26:45 PM CST, Jason M ***@***.***> wrote:  
 
 


Not sure why, but bootstrap threw

/bin/bash^M: bad interpreter: No such file or directory

for me, so I had to run

sed -i -e 's/\r$//' bootstrap

to make it work. Just FYI.

**Comment by hack-r** [comment]
Ubuntu WSLOn Nov 12, 2022, at 11:39 PM, Michael Black ***@***.***> wrote:﻿
Git checkout?  On on what platform?
I just checked and boostrap only has 0xa in it.
0000000    2123    622f    6e69    732f    0a68    230a    5220    6e75          #   !   /   b   i   n   /   s   h  nl  nl   #  sp   R   u   n

Mike W9MDB

 

    On Saturday, November 12, 2022 at 07:26:45 PM CST, Jason M ***@***.***> wrote:  
 
 


Not sure why, but bootstrap threw

/bin/bash^M: bad interpreter: No such file or directory

for me, so I had to run

sed -i -e 's/\r$//' bootstrap

to make it work. Just FYI.

**Comment by mdblack98** [comment]
Try this.
https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf
