### ISSUE TITLE
TT Jupiter Problem

### ISSUE THREAD

**Issue by K1VP** [Hamlib/Hamlib#1174]
I am running hamlib as packaged for Debian Sid and have used it for several years without problems to control TT Jupiter and in particular with XDX to set freq on a cluster spot.  Recently that functionality has a problem.  Specifically, when the F function is used to set the Jupiter's freq, it is shifted to the 160M band and the reported freq is @1062MHZ.  Oddly, this seems to occur only when attempting to set the freq for 20M and below.  All other functions work, but the F function does not as described.  I have used rigctl to duplicate the problem. Hamlib seems to work fine with two other rigs in the shack and only the Jupiter is affected so my assumption is it has to do with the setting for that rig.

As a test, I have used the same computer, cable and rig with DXlabs Commander software under Windows 10 and no problems were encountered.  So there must be something in hamlib as packaged in Debian that is causing the problem with the Jupiter.

I believe the serial comm parameters under the DXLabs software was slightly different than the setting for the Jupiter in hamlib in that DXLabs sets RTS to FLOW.

Happy to send additional info, error outputs and run tests if that would be helpful as I really want to use hamlib as I have in the past.

Thank you.

Ed
K1VP

**Comment by mdblack98** [comment]
Are you building Hamlib?
If so please check out the master repo and I hope this is fixed now.
https://github.com/Hamlib/Hamlib

Mike W9MDB

 

    On Monday, December 5, 2022 at 10:06:43 AM CST, K1VP ***@***.***> wrote:  
 
 


I am running hamlib as packaged for Debian Sid and have used it for several years without problems to control TT Jupiter and in particular with XDX to set freq on a cluster spot. Recently that functionality has a problem. Specifically, when the F function is used to set the Jupiter's freq, it is shifted to the 160M band and the reported freq is @1062MHZ. Oddly, this seems to occur only when attempting to set the freq for 20M and below. All other functions work, but the F function does not as described. I have used rigctl to duplicate the problem. Hamlib seems to work fine with two other rigs in the shack and only the Jupiter is affected so my assumption is it has to do with the setting for that rig.

As a test, I have used the same computer, cable and rig with DXlabs Commander software under Windows 10 and no problems were encountered. So there must be something in hamlib as packaged in Debian that is causing the problem with the Jupiter.

I believe the serial comm parameters under the DXLabs software was slightly different than the setting for the Jupiter in hamlib in that DXLabs sets RTS to FLOW.

Happy to send additional info, error outputs and run tests if that would be helpful as I really want to use hamlib as I have in the past.

Thank you.

Ed
K1VP

**Comment by K1VP** [comment]
On Mon, 05 Dec 2022 12:01:09 -0800
Michael Black ***@***.***> wrote:

> Are you building Hamlib?
> If so please check out the master repo and I hope this is fixed now.
> https://github.com/Hamlib/Hamlib
> 

Mike:

I'm not building it and will wait for changes in Debian packages.
I did check the repo info and notice the file you changed reference
Yaesu.  I am curious what changes were made tht affected the parameters
for the Jupiter.

Many thanks for the quick response.
Will let you know if it is fixed later.

-- 
Ed Lawson
Ham Callsign:         K1VP
PGP Key ID:           B80FC40D
PGP Key Fingerprint:  1E3D C1AD AB42 AFAE 2E07 A3F6 F498 6F10 B80F C40D

**Comment by mdblack98** [comment]
It seems the Jupiter was broken  Jan 11, 2022 during another change that was made.

So should be fixed now and will be in 4.5.1 to be released soon.

Mike W9MDB








On Tuesday, December 6, 2022 at 01:44:13 AM CST, K1VP ***@***.***> wrote: 






On Mon, 05 Dec 2022 12:01:09 -0800
Michael Black ***@***.***> wrote:

> Are you building Hamlib?
> If so please check out the master repo and I hope this is fixed now.
> https://github.com/Hamlib/Hamlib
> 

Mike:

I'm not building it and will wait for changes in Debian packages.
I did check the repo info and notice the file you changed reference
Yaesu. I am curious what changes were made tht affected the parameters
for the Jupiter.

Many thanks for the quick response.
Will let you know if it is fixed later.

-- 
Ed Lawson
Ham Callsign: K1VP
PGP Key ID: B80FC40D
PGP Key Fingerprint: 1E3D C1AD AB42 AFAE 2E07 A3F6 F498 6F10 B80F C40D

**Comment by mdblack98** [comment]
If you can go back to 4.4 it should work again.

Mike W9MDB








On Tuesday, December 6, 2022 at 08:37:03 AM CST, Michael Black ***@***.***> wrote: 






It seems the Jupiter was broken  Jan 11, 2022 during another change that was made.

So should be fixed now and will be in 4.5.1 to be released soon.

Mike W9MDB








On Tuesday, December 6, 2022 at 01:44:13 AM CST, K1VP ***@***.***> wrote: 






On Mon, 05 Dec 2022 12:01:09 -0800
Michael Black ***@***.***> wrote:

> Are you building Hamlib?
> If so please check out the master repo and I hope this is fixed now.
> https://github.com/Hamlib/Hamlib
> 

Mike:

I'm not building it and will wait for changes in Debian packages.
I did check the repo info and notice the file you changed reference
Yaesu. I am curious what changes were made tht affected the parameters
for the Jupiter.

Many thanks for the quick response.
Will let you know if it is fixed later.

-- 
Ed Lawson
Ham Callsign: K1VP
PGP Key ID: B80FC40D
PGP Key Fingerprint: 1E3D C1AD AB42 AFAE 2E07 A3F6 F498 6F10 B80F C40D
