### ISSUE TITLE
TX-500 with Digirig not working

### ISSUE THREAD

**Issue by andras** [Hamlib/Hamlib#1188]
Hi there,

I'm trying to make rigctld run after an update of my entire OS, along with the ham-related programs.  Libhamlib, in particular, was working fine (version 4.0-7 in Devuan), but broke on this update (to 4.5-2+b1).

In order to make things easier, I just built the code I checked out from github.  Here is the output of the command using the Kenwood TS-2000 protocol (which used to work in version 4.0-7), `rigctld -m 2014 -r /dev/ttyUSB0 -vvv`:

[2014.txt](https://github.com/Hamlib/Hamlib/files/10226465/2014.txt)

Using the native TX-500 code now in hamlib, `rigctld -m 2050 -r /dev/ttyUSB0 -vvv`, I get this output:

[2050.txt](https://github.com/Hamlib/Hamlib/files/10226491/2050.txt)

While rigctld was running, I also briefly started `pat http` so something tries to use the CAT interface, but the behaviour is essentially the same with other clients (`wsjtx` etc.).  My hardware also hasn't changed, it's a TX-500 with a Digirig interface to the PC.

The Digirig connects for CAT via /dev/ttyUSB0, which is present, regardless of what the logs say.

What am I doing wrong?

**Comment by mdblack98** [comment]
Looks like they must have changed the serial device enumeration.  It's telling you that there is no such device.
Communication timed out /dev/ttyUSB0 No such file or directory 
Try this
lsusbdmesg | grep ttydmesg | grep cu

Should be one of those now and the device info for what you find hopefully helps.
I also found this link talking about a braille device gobbling up /dev/ttyUSB* devices.https://unix.stackexchange.com/questions/218666/how-to-get-dev-ttyusb-to-show-up

Mike W9MDB

**Comment by mdblack98** [comment]
I wonder if you need one of these options
--set-conf=rts_state=ON
--set-conf=dtr_state=ON

Mike W9MDB

**Comment by andras** [comment]
> I wonder if you need one of these options --set-conf=rts_state=ON --set-conf=dtr_state=ON
> 
> Mike W9MDB

Yes, but that's an entirely different issue.  Without a connection to /dev/ttyUSB0, PTT is of lesser importance.

**Comment by mdblack98** [comment]
Please increase your debug level to -vvvvv (5 v's) and send that.

Mike W9MDB

 

    On Monday, December 19, 2022 at 06:02:22 AM CST, andras ***@***.***> wrote:  
 
 



I wonder if you need one of these options --set-conf=rts_state=ON --set-conf=dtr_state=ON

Mike W9MDB


Yes, but that's an entirely different issue. Without a connection to /dev/ttyUSB0, PTT is of lesser importance.

**Comment by mdblack98** [comment]
And please try the latest version..

https://n0nb.users.sourceforge.net/

 Mike W9MDB
    On Monday, December 19, 2022 at 06:02:22 AM CST, andras ***@***.***> wrote:  
 
 



I wonder if you need one of these options --set-conf=rts_state=ON --set-conf=dtr_state=ON

Mike W9MDB


Yes, but that's an entirely different issue. Without a connection to /dev/ttyUSB0, PTT is of lesser importance.

**Comment by andras** [comment]
> And please try the latest version.. https://n0nb.users.sourceforge.net/ Mike W9MDB On Monday, December 19, 2022 at 06:02:22 AM CST, andras ***@***.***> wrote: I wonder if you need one of these options --set-conf=rts_state=ON --set-conf=dtr_state=ON Mike W9MDB Yes, but that's an entirely different issue. Without a connection to /dev/ttyUSB0, PTT is of lesser importance. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Better by a small amount, this time there is only one reference to /dev/ttyUSB0, and it looks like a success.  Still, `pat http` reports after a few seconds that it couldn't establish a network connection on port 4532, thus it couldn't read the frequency.

Here's a new log:

[4.6.txt](https://github.com/Hamlib/Hamlib/files/10262645/4.6.txt)

Version 4.0 is still my only working option for now.

**Comment by mdblack98** [comment]
Looks like the TX-500 was always responding to the PS; command with PS0; which should mean it's not turned on.
So I disabled that.
Try the master repo again.
Mike W9MDB

 

    On Monday, December 19, 2022 at 02:48:54 PM CST, andras ***@***.***> wrote:  
 
 



And please try the latest version.. https://n0nb.users.sourceforge.net/ Mike W9MDB On Monday, December 19, 2022 at 06:02:22 AM CST, andras @.> wrote: I wonder if you need one of these options --set-conf=rts_state=ON --set-conf=dtr_state=ON Mike W9MDB Yes, but that's an entirely different issue. Without a connection to /dev/ttyUSB0, PTT is of lesser importance. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>


Better by a small amount, this time there is only one reference to /dev/ttyUSB0, and it looks like a success. Still, pat http reports after a few seconds that it couldn't establish a network connection on port 4532, thus it couldn't read the frequency.

Here's a new log:

4.6.txt

Version 4.0 is still my only working option for now.

**Comment by andras** [comment]
> Looks like the TX-500 was always responding to the PS; command with PS0; which should mean it's not turned on. So I disabled that. Try the master repo again. Mike W9MDB

Nothing has changed, as far as I can tell:

[r_git.txt](https://github.com/Hamlib/Hamlib/files/10268022/r_git.txt)

**Comment by mdblack98** [comment]
If your last log you were running at 9600 baud which was talking to the rig but now it shows 57600 and the rig is not responding.
Why the baud rate change?  Can you test 9600 again?
Mike W9MDB

 

    On Tuesday, December 20, 2022 at 05:37:47 AM CST, andras ***@***.***> wrote:  
 
 



Looks like the TX-500 was always responding to the PS; command with PS0; which should mean it's not turned on. So I disabled that. Try the master repo again. Mike W9MDB


Nothing has changed, as far as I can tell:

r_git.txt

**Comment by mdblack98** [comment]
I'll add that the manual only indicates 9600 baud available and no ability to change it.
Mike W9MDB

 

    On Tuesday, December 20, 2022 at 08:14:03 AM CST, Michael Black ***@***.***> wrote:  
 
 

If your last log you were running at 9600 baud which was talking to the rig but now it shows 57600 and the rig is not responding.
Why the baud rate change?  Can you test 9600 again?
Mike W9MDB

 

 On Tuesday, December 20, 2022 at 05:37:47 AM CST, andras ***@***.***> wrote: 
 
 



Looks like the TX-500 was always responding to the PS; command with PS0; which should mean it's not turned on. So I disabled that. Try the master repo again. Mike W9MDB


Nothing has changed, as far as I can tell:

r_git.txt

**Comment by andras** [comment]
You're right, it works when I set baud rate yo 9600 (I forgot that option last time).  Thanks a lot!
