### ISSUE TITLE
Problem USB data-USB  Kenwood TS 590SG

### ISSUE THREAD

**Issue by SM5VFE** [Hamlib/Hamlib#1190]
Sometimes problem to change from USB Data to USB mode. When  using USB Data and pressing USB. Radio sends again command for USB Data ( I think) . Solution is to press another mode  (am, fm, cw and finally USB) to ge again in USB mode. 

This was also an issue in Hamlib 4,5 version.

**Comment by mdblack98** [comment]
Running what software?

**Comment by mdblack98** [comment]
And hamlib doesn't do anything without being asked by the controlling program so not sure how this is occurring.

**Comment by SM5VFE** [comment]
rigpi

**Comment by mdblack98** [comment]
That needs be reported to RigPI then.
Hamlib does not force mode at all by itself.
Mike W9MDB

 

    On Wednesday, December 14, 2022 at 04:30:10 PM CST, SM5VFE ***@***.***> wrote:  
 
 


rigpi

**Comment by SM5VFE** [comment]
I have done that will do again. 
Regards from Loic, SM5VFE
