### ISSUE TITLE
ICOM ID-5100 - rigctld Get Power status command failing

### ISSUE THREAD

**Issue by leeott25** [Hamlib/Hamlib#1201]
Periodically rigctld sends fe fe 8c e0 18 fd to the ICOM ID-5100.  The ID-5100 replies with fe fe e0 8c fa fd which is the NG response.  According to the ICOM ID-5100 Full Manual (see page 13-17), the 18 cmd is only a set command.  It expects a sub command.  Below is a section of the log from rigctld.

write_block(): TX 6 bytes, method=2
0000    fe fe 8c e0 18 fd                                   ......
read_string_generic called, rxmax=200 direct=1, expected_len=1
read_string_generic(): RX 6 characters, direct=1
0000    fe fe 8c e0 18 fd                                   ......
icom_one_transaction: DEBUG retval=6, frm_len=6, cmd=0x18
read_string_generic called, rxmax=200 direct=1, expected_len=1
read_string_generic(): RX 6 characters, direct=1
0000    fe fe e0 8c fa fd                                   ......
                     -21:frame.c(352):icom_one_transaction returning(-9) Command rejected by the rig

Command rejected by the rig
Command rejected by the rig

                     -22:frame.c(455):icom_transaction returning(-9) Command rejected by the rig

                     -23:icom.c(8090):icom_get_powerstat returning(-9) Command rejected by the rig

                     -24:rig.c(6045):rig_get_powerstat returning(-9) Command rejected by the rig

rigctl_parse: rig_powerstat is not on = 0

**Comment by mdblack98** [comment]
I've disabled get_powerstat for the ID-5100. 
So this is step#1 to getting things working correctly.
Are you able to compile the master repo?
Mike W9MDB

 

    On Monday, January 2, 2023 at 08:07:25 AM CST, leeott25 ***@***.***> wrote:  
 
 


Periodically rigctld sends fe fe 8c e0 18 fd to the ICOM ID-5100. The ID-5100 replies with fe fe e0 8c fa fd which is the NG response. According to the ICOM ID-5100 Full Manual (see page 13-17), the 18 cmd is only a set command. It expects a sub command. Below is a section of the log from rigctld.

write_block(): TX 6 bytes, method=2
0000 fe fe 8c e0 18 fd ......
read_string_generic called, rxmax=200 direct=1, expected_len=1
read_string_generic(): RX 6 characters, direct=1
0000 fe fe 8c e0 18 fd ......
icom_one_transaction: DEBUG retval=6, frm_len=6, cmd=0x18
read_string_generic called, rxmax=200 direct=1, expected_len=1
read_string_generic(): RX 6 characters, direct=1
0000 fe fe e0 8c fa fd ......
-21:frame.c(352):icom_one_transaction returning(-9) Command rejected by the rig

Command rejected by the rig
Command rejected by the rig
                 -22:frame.c(455):icom_transaction returning(-9) Command rejected by the rig

                 -23:icom.c(8090):icom_get_powerstat returning(-9) Command rejected by the rig

                 -24:rig.c(6045):rig_get_powerstat returning(-9) Command rejected by the rig

rigctl_parse: rig_powerstat is not on = 0
