### ISSUE TITLE
RPI OS update seems to break hamlib

### ISSUE THREAD

**Issue by murtrah57** [Hamlib/Hamlib#1207]
I just did the latest updates to the RPI OS and packages. Now rigctld and rotctld will not run.

**Comment by mdblack98** [comment]
I need a whole lot more information than "will not run".  I assume there's an error of some sort?

Mike W9MDB








On Saturday, January 7, 2023 at 07:52:15 AM CST, murtrah57 ***@***.***> wrote: 







I just did the latest updates to the RPI OS and packages. Now rigctld and rotctld will not run.

**Comment by murtrah57** [comment]
when I try to run either rigctl or rotctl here is what I get:

pi@hampi:~ $ rigctl
rigctl: symbol lookup error: rigctl: undefined symbol: lock_mode
pi@hampi:~ $ rotctl
rotctl: symbol lookup error: rotctl: undefined symbol: debugmsgsave2
pi@hampi:~ $

**Comment by murtrah57** [comment]
I have a crontab entry that autostarts both rigctld and rotctld on startup. It also checks once per minute to see if they are running. If not it restarts them. My logs show both rigctld and rotctld are both trying to be restarted every minute. 

Everything was working fine before I did a package update this morning.

**Comment by mdblack98** [comment]
Please run rigctld manually with "-vvvvv" added and send me a capture of the log.

Mike







On Saturday, January 7, 2023 at 08:09:34 AM CST, murtrah57 ***@***.***> wrote: 







I have a crontab entry that autostarts both rigctld and rotctld on startup. It also checks once per minute to see if they are running. If not it restarts them. My logs show both rigctld and rotctld are both trying to be restarted every minute.

Everything was working fine before I did a package update this morning.

**Comment by mdblack98** [comment]
Then you have an old libhamlib sitting around.

When you install from source it defaults to /usr/local/bin and you probably have libhamlib.so in /usr/lib/ too.

If you have a hamlib package installed then you need to uninstall it when compiling it yourself.

Mike W9MDB








On Saturday, January 7, 2023 at 08:02:29 AM CST, murtrah57 ***@***.***> wrote: 







when I try to run either rigctl or rotctl here is what I get:

***@***.***:~ $ rigctl
rigctl: symbol lookup error: rigctl: undefined symbol: lock_mode
***@***.***:~ $ rotctl
rotctl: symbol lookup error: rotctl: undefined symbol: debugmsgsave2
***@***.***:~ $

**Comment by murtrah57** [comment]
I did a complete search of my file system from root level down. I have only one copy of libhamlib.so
I do not have another copy or version in /usr/lib

See screen shot attached.

![2023-01-07-094743_1017x665_scrot](https://user-images.githubusercontent.com/96009649/211156624-6619401c-13d1-4d97-bb52-b441bcd8c793.png)

**Comment by murtrah57** [comment]
Not sure why but now it seems to be running again.  ??????
Sorry to have taken up your time.
