### ISSUE TITLE
Timing on NRD-535 is too small

### ISSUE THREAD

**Issue by markjfine** [Hamlib/Hamlib#1210]
Have been debugging some issues on grig using my NRD-535D and discovered that some of the commands were timing out.
Revising the following two lines in rigs/jrc/nrd535.c seem to solve the problem:

```
     .write_delay =  0,`
-    .post_write_delay =  20,
-    .timeout =  200,
+    .post_write_delay =  21,
+    .timeout =  250,
    .retry =  3,
```

**Comment by mdblack98** [comment]
Fixed in e3ac42a6b65246114d5fdc6e98d708f45879d3fb
