### ISSUE TITLE
Possible bug in gemini_set_level()

### ISSUE THREAD

**Issue by dforsi** [Hamlib/Hamlib#1253]
The `return` at line 285 seems wrong because it's just before a `break` and therefore the `cmd` variable is never used, and the check at line 291 seems it should be "equal" instead of "not equal". https://github.com/Hamlib/Hamlib/blob/18c4eb46315ef44bdf22f5ac7774ba017e186564/amplifiers/gemini/gemini.c#L269-L297

**Comment by mdblack98** [comment]
Fixed in 3fa423c63dd19a47bd48cc60eac9b08f4a48caca
