### ISSUE TITLE
Rotctl model 405 does not return elevation angle from second device

### ISSUE THREAD

**Issue by NUCARADO** [Hamlib/Hamlib#1258]
The Green Heron RT-21 uses two different devices, one for azimuth and one for elevation. Support for the elevation device appears to be incomplete. Elevation value is never queried on the second device.

Rotator command: p
rot_get_position called
rt21_rot_get_position called
rotorez_send_priv_cmd called
write_block(): TX 4 bytes, method=2
0000    42 49 31 3b                                         BI1;
read_string_generic called, rxmax=7 direct=1, expected_len=1
read_string_generic(): RX 5 characters, direct=1
0000    32 30 2e 30 3b                                      20.0;
rt21_rot_get_position: "20.0;" after conversion = 20.0
rt21_rot_get_position: azimuth = 20.0 deg; elevation = 0.0 deg
rot_get_position: got az=20.00, el=0.00
Azimuth: 20.00
Elevation: 0.00

In Rotorez.c:

*elevation = 0.0;   /* RT-21 backend does not support el at this time. */

**Comment by mdblack98** [comment]
No news is good news I guess
