### ISSUE TITLE
Rotctl model 405 does not send set_position command to second device

### ISSUE THREAD

**Issue by NUCARADO** [Hamlib/Hamlib#1259]
The Green Heron RT-21 uses two different devices, one for azimuth and one for elevation. Support for the elevation device appears to be incomplete. Rotctl reports the info it intends to send to the second device but it is never sent.

Rotator command: P
Azimuth: 0
Elevation: 20
rot_set_position called az=0.00 el=20.00
rot_set_position: south_zero=0
rt21_rot_set_position called
rotorez_send_priv_cmd called
write_block(): TX 10 bytes, method=2
0000    41 50 31 30 30 30 2e 30 0d 3b                       AP1000.0.;
rotorez_send_priv_cmd2 called
;write_block(): TX 10 bytes, method=2
0000    41 50 31 30 32 30 2e 30 0d 3b                       AP1020.0.;

interceptty shows traffic to the first (-r) device (the "AP1000.0.;" above) but nothing to the second (-R) device.

**Comment by mdblack98** [comment]
No news is good news I guess
