### ISSUE TITLE
Rotctl model 405 has a default min and max elevation of zero

### ISSUE THREAD

**Issue by NUCARADO** [Hamlib/Hamlib#1260]
Max elevation should be 90 instead of 0.

**Comment by mdblack98** [comment]
That's what it says...where do you see 0?

max_el: "Maximum rotator elevation in degrees"
	Default: 90, Value: 90.000000
	Range: -90.0..180.0, step 0.0

**Comment by NUCARADO** [comment]
I can't seem to reproduce the issue now. I might have been testing 403 when I couldn't get 405 to work.
