### ISSUE TITLE
Kenwood TS-890 - messages showing different datasize from expected

### ISSUE THREAD

**Issue by Tyrbiter** [Hamlib/Hamlib#1298]
I'm seeing quite a few of these in freedv debug output:

kenwood_safe_transaction called, cmd=IF, expected=37
kenwood_transaction called cmd=IF datasize=128

different rig commands give different numbers, so we have:

kenwood_safe_transaction called, cmd=FA, expected=13
kenwood_transaction called cmd=FA datasize=50

and:

kenwood_safe_transaction called, cmd=MD, expected=3
kenwood_transaction called cmd=MD datasize=6

I don't know if they are significant or if hamlib just deals with the data returned and doesn't care about the extra characters. Thought I would ask.

**Comment by mdblack98** [comment]
It's just showing the buffer size passed in .  The expected value is what is important.
I could suppress that message as long as the buffer size is > the expected.
