### ISSUE TITLE
Can't configure logs output stream in hamlib python bindings

### ISSUE THREAD

**Issue by notsleep196** [Hamlib/Hamlib#1307]
Hello!

I am currently working with the Hamlib python bindings and have encountered an issue with redirecting Hamlib messages. I noticed that there is no way to use the rig_set_debug_file() function from the Hamlib python bindings, which means that I am unable to redirect logs to any stream other than stderr.

The main problem is that this function gets FILE* as parameter that is rather difficult to create in python.

I would be grateful for a hint on how to setup logging to other places (e.g to file) in Hamlib python bindings if it is possible. I didn't find any solution. I hope that it will be fixed in future releases if this is an issue

**Comment by mdblack98** [comment]
New function added
rig_set_debug_filename(char *filename)
Will log to the old debug output where it is being redirected to.
Will log any error opening the filename to the old logging path and return NULL so be sure to check the return vaue for non-NULL.
