### ISSUE TITLE
Yaesu FTDX101D

### ISSUE THREAD

**Issue by RicoDG5BQ** [Hamlib/Hamlib#131]
Hello,
I would love to see support for Yaesus new FTDX11D.

73

**Comment by N0NB** [comment]
Does the FT-100 work?
de Mike W9MDB
 

    On Wednesday, October 9, 2019, 01:58:12 AM CDT, RicoDG5BQ <notifications@github.com> wrote:  
 
 
Hello,
I would love to see support for Yaesus new FTDX11D.

73

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
_______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer

**Comment by RicoDG5BQ** [comment]
Hi Nate,

I didn’t try the FT-100 
But of course I made a mistake. It should read FTDX101D. 
73

Von meinem iPhone gesendet

> Am 09.10.2019 um 14:39 schrieb Nate Bargmann <notifications@github.com>:
> 
> ﻿
> Does the FT-100 work?
> de Mike W9MDB
> 
>

**Comment by mdblack98** [comment]
Were you able to test the FT-100?  If that works I'll make an entry for the DX101.
de Mike W9MDB
 

    On Wednesday, October 9, 2019, 08:10:26 AM CDT, RicoDG5BQ <notifications@github.com> wrote:  
 
 Hi Nate,

I didn’t try the FT-100 
But of course I made a mistake. It should read FTDX101D. 
73

Von meinem iPhone gesendet

> Am 09.10.2019 um 14:39 schrieb Nate Bargmann <notifications@github.com>:
> 
> ﻿
> Does the FT-100 work?
> de Mike W9MDB
> 
>

**Comment by RicoDG5BQ** [comment]
Hi Mike,

I tried the settings for the FT-991. They seem to work just fine. Even though the FTDX101D has two separate transceivers at least switching frequencies and so on on the primary side does work. 

73 de Rico


Von meinem iPhone gesendet

> Am 10.10.2019 um 14:56 schrieb Michael Black <notifications@github.com>:
> 
> ﻿
> Were you able to test the FT-100?  If that works I'll make an entry for the DX101.
> de Mike W9MDB
> 
>

**Comment by RicoDG5BQ** [comment]
Hi again,

for further explanation: I need the settings for my logbook which is cqrlog on my raspberry pi. So the changes that have to be done on the rig are only basic. 
If you’d like I could try the settings for the FT 100 as well later this evening. Just let me know. 

73 de Rico, DG5BQ 



Von meinem iPhone gesendet

> Am 10.10.2019 um 14:56 schrieb Michael Black <notifications@github.com>:
> 
> ﻿
> Were you able to test the FT-100?  If that works I'll make an entry for the DX101.
> de Mike W9MDB
> 
>

**Comment by RicoDG5BQ** [comment]
Hello Mike,

I’ve tried the FT-100 now. It doesn’t work at all.
The only issue I have with the setting for the FT991 on cqrlog is that I cannot switch between the 2 VFO‘s. I only can work and control on the main VFO. Maybe I could configure the sub VFO as the second radio. But I don’t know how. 
On flrig I can switch between the two VFO’s. But in cqrlog I only have the option to control a second radio. 

73 de Rico


Von meinem iPhone gesendet

> Am 10.10.2019 um 14:56 schrieb Michael Black <notifications@github.com>:
> 
> ﻿
> Were you able to test the FT-100?  If that works I'll make an entry for the DX101.
> de Mike W9MDB
> 
>

**Comment by RicoDG5BQ** [comment]
Hi Mike,

maybe this file helps:



73 de Rico, DG5BQ 


Von meinem iPhone gesendet

> Am 10.10.2019 um 14:56 schrieb Michael Black <notifications@github.com>:
> 
> ﻿
> Were you able to test the FT-100?  If that works I'll make an entry for the DX101.
> de Mike W9MDB
> 
>

**Comment by mdblack98** [comment]
I've submitted a patch for the FT-101 so should be in the next release of WSJT-X.
de Mike W9MDB

 

    On Friday, October 11, 2019, 06:35:43 AM CDT, RicoDG5BQ <notifications@github.com> wrote:  
 
 Hi Mike,

maybe this file helps:



73 de Rico, DG5BQ 


Von meinem iPhone gesendet

> Am 10.10.2019 um 14:56 schrieb Michael Black <notifications@github.com>:
> 
> ﻿
> Were you able to test the FT-100? If that works I'll make an entry for the DX101.
> de Mike W9MDB
> 
>

**Comment by N0NB** [comment]
Are you able to compile?  If so try my fork
https://github.com/mdblack98/Hamlib

de Mike W9MDB

 

    On Friday, October 11, 2019, 03:41:49 AM CDT, RicoDG5BQ <notifications@github.com> wrote:  
 
 Hello Mike,

I’ve tried the FT-100 now. It doesn’t work at all.
The only issue I have with the setting for the FT991 on cqrlog is that I cannot switch between the 2 VFO‘s. I only can work and control on the main VFO. Maybe I could configure the sub VFO as the second radio. But I don’t know how. 
On flrig I can switch between the two VFO’s. But in cqrlog I only have the option to control a second radio. 

73 de Rico


Von meinem iPhone gesendet

> Am 10.10.2019 um 14:56 schrieb Michael Black <notifications@github.com>:
> 
> ﻿
> Were you able to test the FT-100? If that works I'll make an entry for the DX101.
> de Mike W9MDB
> 
> 
> On Wednesday, October 9, 2019, 08:10:26 AM CDT, RicoDG5BQ <notifications@github.com> wrote: 
> 
> Hi Nate,
> 
> I didn’t try the FT-100 
> But of course I made a mistake. It should read FTDX101D. 
> 73
> 
> Von meinem iPhone gesendet
> 
> > Am 09.10.2019 um 14:39 schrieb Nate Bargmann <notifications@github.com>:
> > 
> > ﻿
> > Does the FT-100 work?
> > de Mike W9MDB
> > 
> > 
> > On Wednesday, October 9, 2019, 01:58:12 AM CDT, RicoDG5BQ <notifications@github.com> wrote: 
> > 
> > 
> > Hello,
> > I would love to see support for Yaesus new FTDX11D.
> > 
> > 73
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> > _______________________________________________
> > Hamlib-developer mailing list
> > Hamlib-developer@lists.sourceforge.net
> > https://lists.sourceforge.net/lists/listinfo/hamlib-developer
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe._______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer

**Comment by RicoDG5BQ** [comment]
Hi Mike,

Unfortunately I’m not able to compile. 

73 de Rico


Von meinem iPhone gesendet

> Am 11.10.2019 um 14:35 schrieb Nate Bargmann <notifications@github.com>:
> 
> ﻿Are you able to compile?  If so try my fork
> https://github.com/mdblack98/Hamlib
> 
> de Mike W9MDB
> 
> 
>

**Comment by N0NB** [comment]
Contact me off list and I may be able to send you a new rigctld to test.What OS are you running rigctld on?
mdblack98@yahoo.com
de Mike W9MDB

 

    On Friday, October 11, 2019, 08:26:04 AM CDT, RicoDG5BQ <notifications@github.com> wrote:  
 
 Hi Mike,

Unfortunately I’m not able to compile. 

73 de Rico


Von meinem iPhone gesendet

> Am 11.10.2019 um 14:35 schrieb Nate Bargmann <notifications@github.com>:
> 
> ﻿Are you able to compile? If so try my fork
> https://github.com/mdblack98/Hamlib
> 
> de Mike W9MDB
> 
> 
> 
> On Friday, October 11, 2019, 03:41:49 AM CDT, RicoDG5BQ <notifications@github.com> wrote: 
> 
> Hello Mike,
> 
> I’ve tried the FT-100 now. It doesn’t work at all.
> The only issue I have with the setting for the FT991 on cqrlog is that I cannot switch between the 2 VFO‘s. I only can work and control on the main VFO. Maybe I could configure the sub VFO as the second radio. But I don’t know how. 
> On flrig I can switch between the two VFO’s. But in cqrlog I only have the option to control a second radio. 
> 
> 73 de Rico
> 
> 
> Von meinem iPhone gesendet
> 
> > Am 10.10.2019 um 14:56 schrieb Michael Black <notifications@github.com>:
> > 
> > ﻿
> > Were you able to test the FT-100? If that works I'll make an entry for the DX101.
> > de Mike W9MDB
> > 
> > 
> > On Wednesday, October 9, 2019, 08:10:26 AM CDT, RicoDG5BQ <notifications@github.com> wrote: 
> > 
> > Hi Nate,
> > 
> > I didn’t try the FT-100 
> > But of course I made a mistake. It should read FTDX101D. 
> > 73
> > 
> > Von meinem iPhone gesendet
> > 
> > > Am 09.10.2019 um 14:39 schrieb Nate Bargmann <notifications@github.com>:
> > > 
> > > ﻿
> > > Does the FT-100 work?
> > > de Mike W9MDB
> > > 
> > > 
> > > On Wednesday, October 9, 2019, 01:58:12 AM CDT, RicoDG5BQ <notifications@github.com> wrote: 
> > > 
> > > 
> > > Hello,
> > > I would love to see support for Yaesus new FTDX11D.
> > > 
> > > 73
> > > 
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub, or mute the thread.
> > > _______________________________________________
> > > Hamlib-developer mailing list
> > > Hamlib-developer@lists.sourceforge.net
> > > https://lists.sourceforge.net/lists/listinfo/hamlib-developer
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub, or mute the thread.
> > 
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly, view it on GitHub, or unsubscribe._______________________________________________
> Hamlib-developer mailing list
> Hamlib-developer@lists.sourceforge.net
> https://lists.sourceforge.net/lists/listinfo/hamlib-developer
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe._______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer

**Comment by RicoDG5BQ** [comment]
Hi Mike,
That would be absolutely perfect. I just wir an email to the address you gave me. 
Thank you very much. To be honest: the support you give to me is far more than I expected to get. So thank you so much for your help. 

73 de Rico, DG5BQ 


Von meinem iPhone gesendet

> Am 11.10.2019 um 15:58 schrieb Nate Bargmann <notifications@github.com>:
> 
> ﻿Contact me off list and I may be able to send you a new rigctld to test.What OS are you running rigctld on?
> mdblack98@yahoo.com
> de Mike W9MDB
> 
> 
>

**Comment by mdblack98** [comment]
Fixed
