### ISSUE TITLE
Recent 4.6~git causing WSJTX and FreeDV to take 100% CPU

### ISSUE THREAD

**Issue by Tyrbiter** [Hamlib/Hamlib#1334]
I've just reverted to Fedora's current hamlib packages which are version 4.5.5, this does not take 100% CPU.

It's a recent 4.6~git change during the last few days that has caused it, probably since July  7th.

Thoughts?

**Comment by Tyrbiter** [comment]
https://github.com/Hamlib/Hamlib/commit/5a8bd96427df6dfe34e6d0746c6a92b845da8254 has fixed this.

**Comment by mdblack98** [comment]
Still seeing high CPU usage on Windows after 5a8bd96 -- Linux side of the house is OK.

**Comment by mikaelnousiainen** [comment]
See #1336
