### ISSUE TITLE
C++ Rig Init fails

### ISSUE THREAD

**Issue by eriktunsch** [Hamlib/Hamlib#1340]
Hey, 

when I am using the rigclass.cc, during the init-process (Rig myRig{ RIG_MODEL_IC7300 };), the process crashes. When debugging the libhamlib-4.dll has a access violation in the funtion rig_init()

Hope somebody can help.

Erik

**Comment by mdblack98** [comment]
Have you got some minimal code to demonstrate this?

It  works here.

Mike W9MDB








On Tuesday, July 18, 2023 at 08:35:17 PM CDT, eriktunsch ***@***.***> wrote: 







Hey,

when I am using the rigclass.cc, during the init-process (Rig myRig{ RIG_MODEL_IC7300 };), the process crashes. When debugging the libhamlib-4.dll has a access violation in the funtion rig_init()

Hope somebody can help.

Erik

**Comment by mdblack98** [comment]
Linux or Windows?

It works here on Linux.

g++ -g -o testcpp testcpp.cc -lhamlib++

gdb rigtest
(gdb) run

Mike W9MDB



On Wednesday, July 19, 2023 at 07:07:44 AM CDT, eriktunsch ***@***.***> wrote: 







I am using the example c++ code:

/*

    * Hamlib sample C++ program
*/

#include 
#include <hamlib/rigclass.h>

int main(int argc, char* argv[])
{
Rig myRig{ RIG_MODEL_IC7300 };
try {
    myRig.setConf("rig_pathname", "COM8");
    myRig.open();
    myRig.setFreq(MHz(144));
    std::cout << myRig.getLevelI(RIG_LEVEL_STRENGTH) << "dB" << std::endl;
    std::cout << "Modes for freq 14.332: " << myRig.RngRxModes(MHz(14.332)) << std::endl;
    myRig.close();
}
catch (const RigException& Ex) {
    Ex.print();
    return 1;
}

return 0;

}

with the rigclass.cc

**Comment by eriktunsch** [comment]
I am running windows with msvc compiler.

**Comment by mdblack98** [comment]
Do you have a project you can share?

Have you tried stepping though the debugger?

Mike W9MDB








On Wednesday, July 19, 2023 at 09:08:09 AM CDT, eriktunsch ***@***.***> wrote: 







I am running windows with msvc compiler.

**Comment by eriktunsch** [comment]
I found out, it needed to be compiled by gcc.

Thank You!
