### ISSUE TITLE
FTDX101 Firmware update 4000Hz width error

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#1356]
New firmware has added at least one new 4000Hz width for data modes....have to see if it's just SH019 or more than that.
Hamlib error. Invalid parameter while getting current VFO mode' in PKTUSB or PKTLSB

**Comment by Tyrbiter** [comment]
Also applies to the FTDX10, new firmware released a few days ago for that too.

**Comment by mdblack98** [comment]
The patch I just put in fixes the FTDX10 too.

Mike W9MDB







On Saturday, August 5, 2023 at 10:01:29 AM CDT, Brian ***@***.***> wrote: 







Also applies to the FTDX10, new firmware released a few days ago for that too.

**Comment by Tyrbiter** [comment]
Ah, good. I hope it also works for the FT-710.

**Comment by mdblack98** [comment]
The FT-710 wasn't covered but I just patched it.
Looks the same as FTDX101D/MP and FTDX10 now.

Mike W9MDB








On Saturday, August 5, 2023 at 11:59:54 AM CDT, Brian ***@***.***> wrote: 







Ah, good. I hope it also works for the FT-710.
