### ISSUE TITLE
PTT not working

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#1419]
As of 2023-11-08 ptt is not  working with WSJT-X.
Modification of rig_cache structure messed up structure alignment in this commit
337fb0f3e5b7b83c8d28481d516587cc9469e304

**Comment by GeoBaltz** [comment]
Goes back farther than this. Previous commit (6cb17e49) "Add post_ptt_delay for situations..." added item to struct hamlib_port_t that caused the structure mis-alignment.
