### ISSUE TITLE
Need  RIG_LEVEL_SWR implemented

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#1423]
RIG_LEVEL_SWR needs to added to the following rigs
TS-990

**Comment by GeoBaltz** [comment]
The TS-990 RM command has the same problem as the TS-890S - if the rig has recording turned on, the ALC value is always returned by 'RM;' as the first part of the response, and there's no way to turn it off.  I'll try to generate a PR to use the ts890.c code I wrote for the TS-990.

**Comment by mdblack98** [comment]
Does it return two RM status messages or just ALC?  Can you show me the reply to the RM; command in this situation?

**Comment by mdblack98** [comment]
I believe this has been fixed
