### ISSUE TITLE
Build fails on MAC network.c - include <inux/wireless.h>

### ISSUE THREAD

**Issue by mantar10** [Hamlib/Hamlib#1430]
CC       extamp.lo
../../src/src/network.c:1040:10: fatal error: 'linux/wireless.h' file not found
#include <linux/wireless.h>
This is on OSX Mojave 10.14.6 intel mac pro.
Built fine on 11/15/2023
I think commit c1780b19f4a30697588da277db579825f3698516 broke the build on MAC

**Comment by mdblack98** [comment]
Try the latest....

Mike W9MDB








On Thursday, November 16, 2023 at 03:33:10 PM CST, mantar10 ***@***.***> wrote: 







CC extamp.lo
../../src/src/network.c:1040:10: fatal error: 'linux/wireless.h' file not found
#include <linux/wireless.h>
This is on OSX Mojave 10.14.6 intel mac pro.
Built fine on 11/15/2023
I think commit c1780b1 broke the build on MAC

**Comment by mantar10** [comment]
Builds fine Now - Thanks !!!
