### ISSUE TITLE
Python missing doc.

### ISSUE THREAD

**Issue by ve2tmq** [Hamlib/Hamlib#1446]
I'm trying to use cm108 with python.  Reading code are not helpfull. Do  you have doc about Hamlib class python or some sample code using cm108?

Thanks for your help.

**Comment by echo-gravitas** [comment]
Same here. I just compiled Hamlib 4.5.5 for my macOS to use with Python. I also have successfully connected my IC-705 with `rigctl` directly.

Now I wonder how to work with the `Rig` class from Hamlib in Python. I'm quite new in Python but as a web developer I'm good in understanding docs. Is there any proper API documentation?

Vy 73 de Ralph HB3XCO

**Comment by mdblack98** [comment]
You'll find some python examples in the "bindings" directory.
Other than that to get you started there is no other documentation.

Mike W9MDB








On Sunday, December 1, 2024 at 12:57:00 PM CST, Ralph Bolliger ***@***.***> wrote: 







Same here. I just compiled Hamlib 4.5.5 for my macOS to use with Python. I also have successfully connected my IC-705 with rigctl directly.

Now I wonder how to work with the Rig class from Hamlib in Python. I'm quite new in Python but as a web developer I'm good in understanding docs. Is there any proper API documentation?

Vy 73 de Ralph HB3XCO

**Comment by echo-gravitas** [comment]
Roger that. Thank you!

**Comment by mdblack98** [comment]
If that's good enough can we close this issue?

**Comment by echo-gravitas** [comment]
Yes, it's good enough for me. Already working with it.
Close the issue if you like.

**Comment by N0NB** [comment]
* On 2024 01 Dec 12:57 -0600, Ralph Bolliger wrote:
> Same here. I just compiled Hamlib 4.5.5 for my macOS to use with
> Python. I also have successfully connected my IC-705 with `rigctl`
> directly.
> 
> Now I wonder how to work with the `Rig` class from Hamlib in Python.
> I'm quite new in Python but as a web developer I'm good in
> understanding docs. Is there any proper API documentation?

As Mike suggests, there is a script, py3test.py, that may prove helpful
or not.  It is likely not a very Pythonic example just being a script
that steps through various calls.

There are likely better ways to create the bindings than Swig, but I
leave that to someone who knows what they're doing.

73, Nate

-- 
"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."
Web: https://www.n0nb.us
Projects: https://github.com/N0NB
GPG fingerprint: 82D6 4F6B 0E67 CD41 F689 BBA6 FB2C 5130 D55A 8819
