### ISSUE TITLE
Raspberry Pi Bookworm, RPi5, CM4 path issue with rig_settings.

### ISSUE THREAD

**Issue by kc9xg** [Hamlib/Hamlib#1512]
Raspberry Pi bookworm, path issue, with rig_settings, excerpts below.

RPi5 Hamlib in /home/bill/github/Hamlib
rigctld Hamlib 4.5.4 Jan 10 01:31:41Z 2023 SHA=921cc5
rigctld -m 2040 -r /dev/ttyUSB0 -s 9600 -t 4532 -vvvvv -Z
rig_settings_get_path: path=/home/bill/.config//home/bill/hamlib_settings
rig_settings_load_all: settings_file (/home/bill/.config//home/bill/hamlib_settings): No such file or directory
rig_open: cwd=/home/bill
rig_open: /home/bill/.config//home/bill/hamlib_settings does not exist

CM4 HamLib in /home/CM4/github/Hamlib
rigctl Hamlib 4.5.4 Jan 10 01:31:41Z 2023 SHA=921cc5
rigctld -m 2040 -r /dev/ttyUSB0 -s 9600 -t 4532 -vvvvv -Z
rig_settings_get_path: path=/home/CM4/.config//home/CM4/hamlib_settings
rig_settings_load_all: settings_file (/home/CM4/.config//home/CM4/hamlib_settings): No such file or directory
rig_open: cwd=/home/CM4
rig_open: /home/CM4/.config//home/CM4/hamlib_settings does not exist

Bill KC9XG

**Comment by mdblack98** [comment]
Not an error -- just showing expected paths for hamlib_settings file.
