### ISSUE TITLE
GPIO PTT broken as of recent Linux kernel updates

### ISSUE THREAD

**Issue by aschuhardt** [Hamlib/Hamlib#1538]
## Device

- Platform: Raspberry Pi 4B
- OS: Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux

## Background

The [sysfs GPIO interface](https://docs.kernel.org/admin-guide/abi-obsolete.html#abi-sys-class-gpio) was removed in a recent Linux kernel update:

> This ABI is obsoleted by [testing/gpio-cdev](https://docs.kernel.org/admin-guide/abi-testing.html#abi-file-testing-gpio-cdev) and will be removed after 2020.

See this blog post for more background info: https://waldorf.waveform.org.uk/2022/the-one-where-dave-breaks-stuff.html

I found out about this while trying to troubleshoot the below error and stumbling across this forum response: https://forums.raspberrypi.com/viewtopic.php?t=359540#p2157021

## Hamlib Error

The effect of this is that [the Hamlib code](https://github.com/Hamlib/Hamlib/blob/master/src/gpio.c#L41) which relies on using `/sys/class/gpio` to manage GPIO ports will now throw an IO error.

```
$ sudo rigctl -P GPIO -p 4 -vv
GPIO4 direction (using /sys/class/gpio/gpio4/direction): No such file or directory
rig_open: cannot open PTT device "GPIO4"
rig_open: error = rigctl_parse.c(1974):set_conf return(0)
 1:rig.c(817):rig_open entered
rig_settings_get_path: path=/root/.hamlib_settings
rig_settings_load_all: settings_file (/root/.hamlib_settings): No such file or directory
rig_open: cwd=/home/aschuhardt
rig_open: /home/aschuhardt/hamlib_settings does not exist
rig_open: async_data_enable=0, async_data_supported=0
GPIO4 direction (using /sys/class/gpio/gpio4/direction): No such file or directory
rig_open: cannot open PTT device "GPIO4"
 1:rig.c(1237):rig_open returning(-6) IO error

IO error
 (null) No such file or directory
```

Attempting to manually open the GPIO device with the method used by Hamlib confirms that this is no longer possible:

```
$ sudo echo 4 > /sys/class/gpio/export      
echo: write error: Invalid argument
```

**Comment by aschuhardt** [comment]
I'll start on a PR to integrate [libgpiod](https://github.com/brgl/libgpiod).

**Comment by mattbk** [comment]
Should this have been marked completed? It looks like #1539 was reverted in #1551.

**Comment by aschuhardt** [comment]
> Should this have been marked completed? It looks like [#1539](https://github.com/Hamlib/Hamlib/pull/1539) was reverted in [#1551](https://github.com/Hamlib/Hamlib/pull/1551).

It was fixed before it was reverted. I don't know why it was reverted and I don't have a means of testing this at the moment.
