### ISSUE TITLE
Connect rigctld to ICOM via LAN or WiFi

### ISSUE THREAD

**Issue by formtapez** [Hamlib/Hamlib#1567]
Is it possible to connect rigctld to an ICOM radio like IC-9700 or IC-705 via its UDP-Protocol on LAN/WiFi?

**Comment by mdblack98** [comment]
You have to use RS-BA1 software -- that will allow you to use audio too.

https://www.youtube.com/watch?v=Yrn8HB7qLfA

Mike W9MDB
