### ISSUE TITLE
IC-9700 reports incorrect power

### ISSUE THREAD

**Issue by jeffpc** [Hamlib/Hamlib#1613]
The ICOM IC-9700 has 3 bands.  Each band has a different maximum power:
* 2m has a max of 100W
* 70cm has a max of 75W
* 23cm has a max of 10W

hamlib misreports the currently selected power because it doesn't seem to scale the percentage of max power by the max power for that band.  For example, if one selects 60% on 23cm, hamlib will report 60W instead of 6W.

Looking at hamlib's code, it looks like `icom_power2mW` special cases IC-705 and IC-905 (making the assumption that 10W is the max on all bands; I don't know if that's correct), but assumes that all other models are 100W max on all bands. The `icom_mW2power` function just assumes 100W max regardless of model or band.

**Comment by mdblack98** [comment]
Fixed in 76a1a589c900fe1d7b7e0b3ba7dc3ea6a9c70925
