### ISSUE TITLE
Kenwood (at least TS-480SAT and TS-590S) impossible set NR2 mode

### ISSUE THREAD

**Issue by rz4ag** [Hamlib/Hamlib#1625]
commands from rigctl:

Rig command: U VFOA NR 0
Rig command: u VFOA NR
Func: 0

Rig command: U VFOA NR 1
Rig command: u VFOA NR
Func: 1
Rig command: U VFOA NR 1
Rig command: u VFOA NR
Func: 1

if NR 2 is selected manually on transiver:
Rig command: u VFOA NR
Func: 2

**Comment by mdblack98** [comment]
u NR2
U NR2 1
U NR2 0

There's a 2nd way that was not implemented for the TS480 and TS590 but I just fixed that.

U NR 2

Mike W9MDB






On Sunday, October 27, 2024 at 02:59:26 PM CDT, rz4ag ***@***.***> wrote: 







commands from rigctl:

Rig command: U VFOA NR 0
Rig command: u VFOA NR
Func: 0

Rig command: U VFOA NR 1
Rig command: u VFOA NR
Func: 1
Rig command: U VFOA NR 1
Rig command: u VFOA NR
Func: 1

if NR 2 is selected manually on transiver:
Rig command: u VFOA NR
Func: 2

**Comment by rz4ag** [comment]
Checked updated kenwood.* 
It works correct
