### ISSUE TITLE
Latest merge breaks my IC-R8600

### ISSUE THREAD

**Issue by malcolmh** [Hamlib/Hamlib#166]
I merged the latest upstream with my fork & rebuilt. Now I get "rig_open: error = Invalid parameter" when I run rigctl.

Attached is my console output showing the previous rigctl startup, the rebuild and then the resulting rigctl startup.
[hamlib console log.zip](https://github.com/Hamlib/Hamlib/files/4021752/hamlib.console.log.zip)

**Comment by mdblack98** [comment]
Try my latest fork -- hopefully works for you now.
https://github.com/mdblack98/Hamlib


 

    On Saturday, January 4, 2020, 04:07:36 AM CST, Malcolm Herring <notifications@github.com> wrote:  
 
 
I merged the latest upstream with my fork & rebuilt. Now I get "rig_open: error = Invalid parameter" when I run rigctl.

Attached is my console output showing the previous rigctl startup, the rebuild and then the resulting rigctl startup.
hamlib console log.zip

**Comment by malcolmh** [comment]
OK, that hit the spot! - Thanks.
