### ISSUE TITLE
Flex 6xxx interface sets mode to first mode in list (narrowest)

### ISSUE THREAD

**Issue by RocketNJ** [Hamlib/Hamlib#206]
Hi All,

Log4OM V2 ver 2.2.4 now supports IP connection to the Flex 6xxx series radios using Hamlib. 

The issue I am finding is when clicking on a DX spot in the cluster it is QSYing, setting mode, then setting RX filter to narrowest for that mode (50 Hz on CW, 1.8 kHz on SSB). 

OmniRig does not exhibit this behavior.

Is there a way to have Hamlib QSY and set mode but NOT set filter?

Thanks from Hamlib newbie.

Dave wo2x

**Comment by mdblack98** [comment]
Log4OM must be asking for the filter to be set.  There's a RIG_PASSBAND_NOCHANGE they could pass in that would not set the filter.
Either you have to set your filter yourself to what you want it to be so when it is set it is what you want or report the problem to Log4OM support forum.
