### ISSUE TITLE
dBm reading for icom IC-R9500

### ISSUE THREAD

**Issue by digrx** [Hamlib/Hamlib#21]
Is it possible to add a command to read received signal level in dBm ?
There is a command to read in dBm in the manual,
but i don't know how to implement it.

**Comment by mdblack98** [comment]
Are you available to test a fix for this?
Please contact me offline at mdblack98@yahoo.com
de Mike W9MDB

**Comment by mdblack98** [comment]
Patch submitted.

**Comment by digrx** [comment]
Thanks for the patch
Unfortunetly I can not test it because I have no longer acces to R9500.
