### ISSUE TITLE
Testing github email issues#2

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#212]
Testing github email since Nate change procmail

**Comment by mdblack98** [comment]
Comment done on github

**Comment by N0NB** [comment]
Will these go to the mailing list now?

**Comment by mdblack98** [comment]
It doesn't look like it.  At least I didn't see this issue on the list.  Did you get it Nate?

 

    On Wednesday, April 1, 2020, 06:54:36 AM CDT, Nate Bargmann <notifications@github.com> wrote:  
 
 


Will these go to the mailing list now?

**Comment by mdblack98g** [comment]
Testing this issue again

**Comment by mdblack98** [comment]
Testing this issue from my primary account

**Comment by mdblack98** [comment]
Replying from my primary account.

 

    On Monday, April 6, 2020, 02:13:39 PM CDT, mdblack98g <notifications@github.com> wrote:  
 
 


Testing this issue again
