### ISSUE TITLE
rictl does not exit when failing to open rig

### ISSUE THREAD

**Issue by dwery** [Hamlib/Hamlib#213]
On line 538, the exit call is commented
`//        exit(2);
`

**Comment by mdblack98** [comment]
Fixed...had temporarily done that for testing rig commands on rigs I don't have...it's now an option to ignore rig open errors.
de Mike W9MDB

 

    On Sunday, April 5, 2020, 11:22:29 PM CDT, dwery <notifications@github.com> wrote:  
 
 


On line 538, the exit call is commented
// exit(2);
