### ISSUE TITLE
Testing github email issues#3

### ISSUE THREAD

**Issue by mdblack98g** [Hamlib/Hamlib#215]
Testing with a secondary email address to see if it goes through to mdblack98@yahoo.com

**Comment by mdblack98g** [comment]
It works

**Comment by mdblack98** [comment]
And does the reply show from me?

 

    On Monday, April 6, 2020, 02:10:56 PM CDT, mdblack98g <notifications@github.com> wrote:  
 
 


Testing with a secondary email address to see if it goes through to mdblack98@yahoo.com
