### ISSUE TITLE
v3.3 win32/64 .exe refuses to install

### ISSUE THREAD

**Issue by intelmation** [Hamlib/Hamlib#218]
installer bombs on locating .dll files

**Comment by mdblack98** [comment]
I has to be installed as Administrator
de MIke W9MDB

 

    On Tuesday, April 14, 2020, 02:16:50 PM CDT, Tiim <notifications@github.com> wrote:  
 
 


installer bombs on locating .dll files

**Comment by intelmation** [comment]
Sorry, I'm a n00b at this

thx and 73
