### ISSUE TITLE
Not compatible with the latest uhd

### ISSUE THREAD

**Issue by FFY00** [Hamlib/Hamlib#355]
```
usrp_impl.cc:35:10: fatal error: usrp_standard.h: No such file or directory
   35 | #include <usrp_standard.h>
```

**Comment by mdblack98** [comment]
What software package is uhd?
Mike W9MDB

 

    On Thursday, July 30, 2020, 07:46:18 AM CDT, Filipe Laíns <notifications@github.com> wrote:  
 
 

usrp_impl.cc:35:10: fatal error: usrp_standard.h: No such file or directory
   35 | #include <usrp_standard.h>

**Comment by FFY00** [comment]
https://github.com/EttusResearch/uhd

Up until now have been building with `sed -i 's|usrp|uhd|g' configure.ac`.

**Comment by mdblack98** [comment]
I assume you have libusrp-dev installed?  That's where that include file is located.
Mike W9MDB

 

    On Thursday, July 30, 2020, 08:21:20 AM CDT, Filipe Laíns <notifications@github.com> wrote:  
 
 


https://github.com/EttusResearch/uhd

Up until now have been building with sed -i 's|usrp|uhd|g' configure.ac.

**Comment by FFY00** [comment]
I am using arch, but I do have UHD installed, all the header files should be present. I am using the latest release, 3.15.0.0, and the file doesn't seem to be shipped there.

**Comment by mdblack98** [comment]
I can compile the latest UHD without USRP being enabled.  So it doesn't appear to be related to UHD.You have --enable-usrp in your config?  
That would be a different problem.
Mike

 

    On Thursday, July 30, 2020, 08:38:06 AM CDT, Filipe Laíns <notifications@github.com> wrote:  
 
 


I am using arch, but I do have UHD installed, all the header files should be present. I am using the latest release, 3.15.0.0, and the file doesn't seem to be shipped there.

**Comment by FFY00** [comment]
I do have it, yes. I want to build with support for it.

**Comment by mdblack98** [comment]
Then you need to install libusrpThat's where the include file is located.Sounds like configure is finding the library but then the build is not finding the include file.Which sounds like you don't have a development package of libusrp.
Mike W9MDB

 

    On Thursday, July 30, 2020, 09:13:57 AM CDT, Filipe Laíns <notifications@github.com> wrote:  
 
 


I do have it, yes. I want to build with support for it.

**Comment by FFY00** [comment]
Oh, I didn't notice libusrp existed. Is there any reason for you to use it instead of the standard libuhd?

By using UHD you automatically get compatibility with the whole SoapySDR environment, enabling devices like the LimeSDR, bladeRF, PlutoSDR, etc.

**Comment by mdblack98** [comment]
Not my code...don't know why that is there other than probably a different interface to the library.
You don't need to enable usrp.You apparently have some part of it installed if it configures with it.
Mike
 

    On Thursday, July 30, 2020, 10:41:26 AM CDT, Filipe Laíns <notifications@github.com> wrote:  
 
 


Oh, I didn't notice libusrp existed. Is there any reason for you to use it instead of the standard libuhd?

By using UHD you automatically get compatibility with the whole SoapySDR environment, enabling devices like the LimeSDR, bladeRF, PlutoSDR, etc.

**Comment by mdblack98** [comment]
This was a user configuration problem.
