### ISSUE TITLE
TYpo in RIG list - FA-SDR

### ISSUE THREAD

**Issue by waterwin** [Hamlib/Hamlib#362]
2515  Funkamatuer            FA-SDR                  0.1             Alpha

should read

2515  Funkamateur            FA-SDR                  0.1             Alpha

**Comment by mdblack98** [comment]
Good eye....got it fixed.
Mike W9MDB

 

    On Wednesday, September 2, 2020, 04:42:08 PM CDT, waterwin <notifications@github.com> wrote:  
 
 


2515 Funkamatuer FA-SDR 0.1 Alpha

should read

2515 Funkamateur FA-SDR 0.1 Alpha
