### ISSUE TITLE
FT817 ft817_set_powerstat for power on dont work

### ISSUE THREAD

**Issue by F4HTB** [Hamlib/Hamlib#363]
Hello, 

Juste a litle message to say that your ft817_set_powerstat dont work.
I have already have this issue in my pyton script, you must send:

0xff, 0xff, 0xff, 0xff, 0xff
and after
0x00, 0x00, 0x00, 0x00, 0x0f

maybe like :

int ft817_set_powerstat(RIG *rig, powerstat_t status)
{
    rig_debug(RIG_DEBUG_VERBOSE, "%s: called\n", __func__);

    switch (status)
    {
    case RIG_POWER_OFF:
        return ft817_send_cmd(rig, FT817_NATIVE_CAT_PWR_OFF);

    case RIG_POWER_ON:
        ft817_send_cmd(rig, { 1, { 0xff, 0xff, 0xff, 0xff, 0xff } });
        return ft817_send_cmd(rig, FT817_NATIVE_CAT_PWR_ON);

    case RIG_POWER_STANDBY:
    default:
        return -RIG_EINVAL;
    }
}

**Comment by mdblack98** [comment]
Please do a pull and test the patch I just made.This should work for the ft857 and ft897 too.
Mike W9MDB

 

    On Thursday, September 3, 2020, 04:46:15 PM CDT, Olivier SCHMITT <notifications@github.com> wrote:  
 
 


Hello,

Juste a litle message to say that your ft817_set_powerstat dont work.
I have already have this issue in my pyton script, you must send:

0xff, 0xff, 0xff, 0xff, 0xff
and after
0x00, 0x00, 0x00, 0x00, 0x0f

maybe like :

int ft817_set_powerstat(RIG *rig, powerstat_t status)
{
rig_debug(RIG_DEBUG_VERBOSE, "%s: called\n", func);
switch (status)
{
case RIG_POWER_OFF:
    return ft817_send_cmd(rig, FT817_NATIVE_CAT_PWR_OFF);

case RIG_POWER_ON:
    ft817_send_cmd(rig, { 1, { 0xff, 0xff, 0xff, 0xff, 0xff } });
    return ft817_send_cmd(rig, FT817_NATIVE_CAT_PWR_ON);

case RIG_POWER_STANDBY:
default:
    return -RIG_EINVAL;
}

}
