### ISSUE TITLE
IC-705 Support

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#364]
Implement IC-705

**Comment by mikaelnousiainen** [comment]
@mdblack98 The IC-7300 and IC-705 caps are now mixed here

**Comment by mikaelnousiainen** [comment]
@mdblack98 I mean that they are in incorrectly set now, can you take a quick look

**Comment by mdblack98** [comment]
Should be fixed now....please check.
Mike W9MDB

 

    On Monday, September 7, 2020, 12:46:08 AM CDT, Mikael Nousiainen <notifications@github.com> wrote:  
 
 


@mdblack98 I mean that they are incorrectly set now, can you take a quick look

**Comment by mikaelnousiainen** [comment]
@mdblack98 All good otherwise, but the highest band on IC-7300 is 4m. (so 2m + 70cm should be removed)

**Comment by mikaelnousiainen** [comment]
@mdblack98 Also, couldn't we use RIG_PARM_BACKLIGHT for setting backlight brightness? Other rigs support it already. I think backlight settings should anyway be in the "parameters" category... There should be no need for a new level, right?

**Comment by mdblack98** [comment]
I reviewed them with the specs so hopefully correct now.

 

    On Monday, September 7, 2020, 08:40:18 AM CDT, Mikael Nousiainen <notifications@github.com> wrote:  
 
 


@mdblack98 All good otherwise, but the highest band on IC-7300 is 4m. (so 2m + 70cm should be removed)

**Comment by mikaelnousiainen** [comment]
@mdblack98 Thanks, now it looks correct.

Still restating my previous comment: Couldn't we use RIG_PARM_BACKLIGHT for setting backlight brightness? Other rigs support it already. I think backlight settings should anyway be in the "parameters" category... There should be no need for a new level, right?
