### ISSUE TITLE
binding for perl, python and tcl fails in hamlib-4.0_rc1 

### ISSUE THREAD

**Issue by dl1jbe** [Hamlib/Hamlib#367]
bindings/hamlib.swg refers in line 250 to a file amplifier.swg which is not in the tar ball.

Digging deeper it looks as if the bindings/hamlib.swg file is not the same as in github repo.

**Comment by mdblack98** [comment]
It was missing from Makefile.am but I think Nate may have to change his distribution script.
Mike W9MDB

 

    On Monday, September 7, 2020, 09:52:49 AM CDT, Thomas Beierlein <notifications@github.com> wrote:  
 
 


bindings/hamlib.swg refers in line 250 to a file amplifier.swg which is not in the tar ball.

Digging deeper it looks as if the bindings/hamlib.swg file is not the same as in github repo.

**Comment by mdblack98** [comment]
Which tarball did you download?
Mike W9MDB

 

    On Monday, September 7, 2020, 09:52:49 AM CDT, Thomas Beierlein <notifications@github.com> wrote:  
 
 


bindings/hamlib.swg refers in line 250 to a file amplifier.swg which is not in the tar ball.

Digging deeper it looks as if the bindings/hamlib.swg file is not the same as in github repo.

**Comment by N0NB** [comment]
If it was missing from the Makefile.am then it will be included when `make dist` is invoked.

**Comment by dl1jbe** [comment]
> Which tarball did you download? Mike W9MDB On Monday, September 7, 2020, 09:52:49 AM CDT, 

hamlib-4.0_rc1.tar.gz from sourceforge.net

**Comment by N0NB** [comment]
Okay, I have cherry-picked all of Mike's commits up to this one into the Hamlib-4.0 branch.  Tom, can you pull from master and verify the fix?  If it's working I'll do an rc2.

**Comment by dl1jbe** [comment]
Give some minutes. I will try.

**Comment by N0NB** [comment]
Thanks!

**Comment by dl1jbe** [comment]
Looks good now. I have cloned Hamlib/hamlib.git from github. Perl and Python bindings got build (the others I did not check atm).

**Comment by N0NB** [comment]
Ok, I can quickly work up an rc2 and upload them.  Thanks, Tom.

**Comment by dl1jbe** [comment]
Your welcome. Glad to help. Btw, first checks with tlf are looking good.

**Comment by N0NB** [comment]
I've been using the master branch of Hamlib with the master branch of Tlf for some time.

Thanks, Tom.

**Comment by dl1jbe** [comment]
Did just a full build from the rc2 tar ball on sourceforge. Works as expected.

**Comment by N0NB** [comment]
* On 2020 07 Sep 13:03 -0500, Thomas Beierlein wrote:
> Did just a full build from the rc2 tar ball on sourceforge. Works as expected. 
> 

Thumbs up!

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: https://www.n0nb.us
Projects: https://github.com/N0NB
GPG fingerprint: 82D6 4F6B 0E67 CD41 F689 BBA6 FB2C 5130 D55A 8819
