### ISSUE TITLE
Yaesu bandwidth 0 not working

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#396]
\\set_mode USB 0 -- does not utilize SH00 command to select the default bandwidth.
Unable to set the roofing filter on FTDX101D too so can't read the bandwidth of the roofing filter.

**Comment by Ian-G3VPX** [comment]
Test with FTdx101D  RPi terminal  rigctl
\send_mode Main LSB -2 sets width = 2400Hz      scope decoded:  SH0014;    SSB bandwidths
\send_mode Main CW -2 sets width = 2000Hz       scope decode:   SH0016;    CW/RTTY/PSK  bandwidths

**Comment by mdblack98** [comment]
That sounds right.This should select the roofing filter now.\send_mode Main LSB 0

 

    On Monday, October 5, 2020, 04:11:31 PM CDT, Ian-G3VPX <notifications@github.com> wrote:  
 
 


Test with FTdx101D RPi terminal rigctl
\send_mode Main LSB -2 sets width = 2400Hz scope decoded: SH0014; SSB bandwidths
\send_mode Main CW -2 sets width = 2000Hz scope decode: SH0016; CW/RTTY/PSK bandwidths
