### ISSUE TITLE
FTdx101D CWPITCH control

### ISSUE THREAD

**Issue by Ian-G3VPX** [Hamlib/Hamlib#407]
FTdx101D  KP command  K  P  P1  P1  ;  P1 is 00 to 75  for  300Hz to 1050Hz

Using command line rigctl:  \get_level Main CWPITCH
300Hz   returns   300
1050Hz   returns   4000

\set_level Main CWPITCH n
n = 300   sets 300Hz
n = 400   sets 320Hz
n = 600  sets  360Hz  scope decode KP06;
n = 1000 sets 440Hz   scope secode KP14;      300 + 10*14 = 440
n = 2000 sets 460Hz
n = 3000 sets 460Hz
n= 4000 sets 460Hz     scope decode KP16;

**Comment by mdblack98** [comment]
Try again...scale was wrong for that.
Mike

 

    On Friday, October 9, 2020, 03:24:55 PM CDT, Ian-G3VPX <notifications@github.com> wrote:  
 
 


FTdx101D KP command K P P1 P1 ; P1 is 00 to 75 for 300Hz to 1050Hz

Using command line rigctl: \get_level Main CWPITCH
300Hz returns 300
1050Hz returns 4000

\set_level Main CWPITCH n
n = 300 sets 300Hz
n = 400 sets 320Hz
n = 600 sets 360Hz scope decode KP06;
n = 1000 sets 440Hz scope secode KP14; 300 + 10*14 = 440
n = 2000 sets 460Hz
n = 3000 sets 460Hz
n= 4000 sets 460Hz scope decode KP16;

**Comment by Ian-G3VPX** [comment]
CWPITCH now working perfectly 300 - 1050Hz
- Sets  correctly from slider control.   Sync reads sets slider and  text freq display matches rig
Ian G3VPX
