### ISSUE TITLE
FTdx101D  \set_vfo   \get_vfo not working

### ISSUE THREAD

**Issue by Ian-G3VPX** [Hamlib/Hamlib#408]
**FTdx101D VFO selection problem**

\get_vfo

Main selected on rig:
v    >   result   =  Main      scope decode VS;    >   VS0;    = correct

Sub Selected on rig 
v    >   result   =  VFOB      scope decode:  VS;  >   VS1;  = correct   *********

\set_vfo    ....    scope decode:   no CAT command sent

V Main
set_vfo: error = Feature not impemented

V VFOA
set_vfo:  error = Invalid parameter

V Sub
set_vfo:   error = Feature not impemented

V VFOB
set_vfo:  error = Invalid parameter

\set_vfo Sub
set_vfo:   error = Feature not impemented

**Comment by Ian-G3VPX** [comment]
\set_vfo Main    and  \set_vfo Sub   ( and \get_vfo )
- working fine at rigctl command line
- Not working in piWebCAT with rigctld   -    nothing on scope on Tx line
I echoed the string (ie \set_vfo Main) from the PHP code line immediately
before the socketwrte  and it looks ok
Is this possible?
Ian   G3VPX

**Comment by mdblack98** [comment]
Seems to work for me talking through rigctld....
pi@piWebCAT:~ $ rigctl -m 2
Rig command: \get_vfoVFO: Sub
Rig command: \set_vfo Main
Rig command: \get_vfoVFO: Main
Rig command: \set_vfo Sub
Rig command: \get_vfoVFO: Sub
Rig command: 



 

    On Saturday, October 10, 2020, 04:58:01 PM CDT, Ian-G3VPX <notifications@github.com> wrote:  
 
 


\set_vfo Main and \set_vfo Sub ( and \get_vfo )
   
   - working fine at rigctl command line
   - Not working in piWebCAT with rigctld - nothing on scope on Tx line   
I echoed the string (ie \set_vfo Main) from the PHP code line immediately   
before the socketwrte and it looks ok   
Is this possible?   
Ian G3VPX

**Comment by Ian-G3VPX** [comment]
This is working fine now   - (rig > piWebCAT   and  piWebCAT > rig)  
... rigctl command line ok
... piWebCAT rigctld ok  
(having to tmeporarily use:  if(cat == 'Sub\n')  ... need to tidy this up and remove '\n' for all returns
   ... most returns are numeric and parseInt ignores '\n'  )
