### ISSUE TITLE
TS-2000 Communication Timeout

### ISSUE THREAD

**Issue by stejand** [Hamlib/Hamlib#41]
I cannot continue a connection to my TS-2000 (using -m 214) because of a communication timeout.  HamLib seems to initially connect and the PC connection indicator comes on my TS-2000.   Then it goes away after a brief time (the rigctl also disconnects and returns the command line with the error text). There is no such problem when I use the TS-440 description with rigctl (even though I am using a TS-2000).  I can control the TS-2000 using the TS-440 device description (e.g. change frequency), staying connected indefinitely.  However, I want to use this on VHF/UHF where the TS-440 doesn't go, There is an error if I try to commanded it to 435MHz using the TS-440 device description.  I have no communication problems with Omnirig, WSJT-x or Ham Radio Deluxe.  The problem seems unique to HamLib and I don't remember having this problem with an older version of HamLib. Is there a problem with the TS-2000 definition?

**Comment by mdblack98** [comment]
Cannot reproduce problem.
