### ISSUE TITLE
FTDX101D TUNE not working

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#411]
U Main TUNER 1 and U Main TUNER 2 both send  AC001; =   tuner  on
BUT
if you change rigctl to send :

U Main TUNER 1    >   AC002;

U Main TUNER 0    >  AC000;

that should be very useful.

Because AC002; switches on the tuner AND then starts a tuner  (about 10 max)

The tuner is then left ON.

Resending AC002; does another tune.

Sending AC000; switches the tuner off.

**Comment by Ian-G3VPX** [comment]
This is still sending AC001;
I thought you were going to change ti to send AC002;
Ian

**Comment by mdblack98** [comment]
Are you opening/closing rigctld every command?  I see it cycling through sockets like crazy.Best if you just keep it open and reconnect if it fails. 

    On Saturday, October 10, 2020, 05:08:20 PM CDT, Ian-G3VPX <notifications@github.com> wrote:  
 
 


This is still sending AC001;
I thought you were going to change ti to send AC002;
Ian

**Comment by mdblack98** [comment]
You don't have the latest version installed.
Mike

 

    On Saturday, October 10, 2020, 05:08:20 PM CDT, Ian-G3VPX <notifications@github.com> wrote:  
 
 


This is still sending AC001;
I thought you were going to change ti to send AC002;
Ian

**Comment by Ian-G3VPX** [comment]
Tuner and Tune buttons now working exactly as planned
- Very effective and fit for purpose
Ian
