### ISSUE TITLE
FTdx101D  NR NB MN ANF \

### ISSUE THREAD

**Issue by Ian-G3VPX** [Hamlib/Hamlib#413]

**Comment by mdblack98** [comment]
I take it this means it must be broken?  Completely?

**Comment by Ian-G3VPX** [comment]
No   - I hit the send key too early

NB NR MN ANF

\set_func Sub NR n  is ok   - sets Sub
\set_func Main NR n  is ok    sets Main

\get_func Main NR    is ok reads Main
\get_func Sub NR   is not ok   reads Main

Likewise NB MN ANF
Only just spotted this because only recently had VFO switching working

(XIT and RIT are ok   ....    act on current VFO)

Ian G3VPX

**Comment by Ian-G3VPX** [comment]
This is fine now
Ian G3VPX
