### ISSUE TITLE
FTdx101d func COMP not working

### ISSUE THREAD

**Issue by Ian-G3VPX** [Hamlib/Hamlib#417]
Must have missed this one ( fixed COMP level and Tx COMP)

u Main COMP
get_func: error = Invalid Paraameter

U Main COMP 1 
set_func: error = Communication bus collision

debug:
[COMP.txt](https://github.com/Hamlib/Hamlib/files/5372399/COMP.txt)

**Comment by mdblack98** [comment]
Try again...101DX has  new format for the command.
Mike

 

    On Tuesday, October 13, 2020, 10:33:57 AM CDT, Ian-G3VPX <notifications@github.com> wrote:  
 
 


Must have missed this one ( fixed COMP level and Tx COMP)

u Main COMP
get_func: error = Invalid Paraameter

U Main COMP 1
set_func: error = Communication bus collision

debug:
COMP.txt

**Comment by Ian-G3VPX** [comment]
U Main COMP 1  / 0    ok

u Main COMP always returns 1

if rig comp on:  u Main COMP   decode:  send:  PR0;   receive: PR01;  correct -  returns 1 = correct

if rig comp off:  u Main COMP   decode:  send:  PR0;   receive: PR00;  correct  BUT  -  returns 1 = incorrect

**Comment by mdblack98** [comment]
Should be working now.

 

    On Thursday, October 15, 2020, 02:48:07 PM CDT, Ian-G3VPX <notifications@github.com> wrote:  
 
 


U Main COMP 1 / 0 ok

u Main COMP always returns 1

if rig comp on: u Main COMP decode: send: PR0; receive: PR01; correct - returns 1 = correct

if rig comp off: u Main COMP decode: send: PR0; receive: PR00; correct BUT - returns 1 = incorrect

**Comment by Ian-G3VPX** [comment]
Fixed in command line rigctl

? not fixed in rigctld
Ian

**Comment by mdblack98** [comment]
You must be running the rigctld in /usr/bin which is an older version.
Mike

 

    On Thursday, October 15, 2020, 04:20:58 PM CDT, Ian-G3VPX <notifications@github.com> wrote:  
 
 


Fixed in command line rigctl

? not fixed in rigctld
Ian

**Comment by Ian-G3VPX** [comment]
This is now working correctly with rigctld

Thanks

Ian
G3VPX
