### ISSUE TITLE
FTDX101 control issues

### ISSUE THREAD

**Issue by mikaelnousiainen** [Hamlib/Hamlib#423]
I've done some thorough testing on an FTDX101 (only accessible to me remotely via Hamlib) and found the following issues with the latest master on Oct 19th 2020.

Rig model in Hamlib is:
```
  1040  Yaesu                  FT-DX101D               20201016.5      Stable      RIG_MODEL_FTDX101D
```

- [x] FM mode is missing (PKTFM is there)
- [x] FM / AM filters cannot be used (only 2 filters?) -- changing filter width has no effect
- [x] Check if FTDX101 supports freely adjustable filter width (filter width 0 in Hamlib)
- [x] MIC GAIN range is incorrect (only 0-40 when it should be 0-100%)
- [x] COMP cannot be turned off (but no error)
- [x] MONITOR cannot be turned on (but no error)
- [x] LOCK cannot be turned off
- [x] Meters added: S-meter, comp meter, RF power meter, current, voltage
- [x] Fixed '+\get_ctcss_tone' fails with response: Communication timed out (error code -5)
- [x] Fixed incorrect scale for RF POWER
- [x] SPLIT verified to work correctly
- [x] RIT/XIT verified to work correctly, removed automatic enabling of RIT/XIT when adjusting offset frequency

I'll be fixing (hopefully most of) these in the coming days and will be updating this issue, but I thought I'd leave this open if I don't get all of them fixed.

**Comment by mikaelnousiainen** [comment]
At least some of these (the filters?) may apply to other Yaesu rigs, like FTDX5000. I'll most likely be able to test FTDX5000 after this rig.

**Comment by mikaelnousiainen** [comment]
@mdblack98 Just a note that I'm currently working on fixing a bunch of issues in Yaesu newcat control commands, will push out changes next week once I have properly tested them.

**Comment by mikaelnousiainen** [comment]
@mdblack98 Would you happen to have any ideas on what the scales for Yaesu meters (S-meter, comp, power output, vdd, idd) are? It's really weird that many rigs have the capability to read these meters, but there seems to be no documentation on what the values actually mean in the official Yaesu CAT manuals...

**Comment by mdblack98** [comment]
Lots of rigs need custom tables -- you can see the FTDX101D swr table for example in newcat.cSWR is usually non-linear so a simple scale doesn't work.
Other values that are linear should work with a simpler scaling factor.
Default scale is 0-255 for example for RFPOWER.  First line here sets either 100 for FT450 or 255 as the default and then other rigs override the 255 if appropriate.
        scale = (newcat_is_rig(rig, RIG_MODEL_FT450)) &&                (newcat_get_rigid(rig) == NC_RIGID_FT450D) ? 100. : 255.;        scale = newcat_is_rig(rig, RIG_MODEL_FT891) ? 100. : scale ;        scale = newcat_is_rig(rig, RIG_MODEL_FT950) ? 100. : scale ;        scale = newcat_is_rig(rig, RIG_MODEL_FT1200) ? 100. : scale ;        scale = newcat_is_rig(rig, RIG_MODEL_FT991) ? 100. : scale ;
Mike W9MDB


 

    On Friday, October 23, 2020, 04:08:00 AM CDT, Mikael Nousiainen <notifications@github.com> wrote:  
 
 


@mdblack98 Would you happen to have any ideas on what the scales for Yaesu meters (S-meter, comp, power output, vdd, idd) are? It's really weird that many rigs have the capability to read these meters, but there seems to be no documentation on what the values actually mean in the official Yaesu CAT manuals...

**Comment by mikaelnousiainen** [comment]
Yeah, the FT-991 S-meter seems to work at least reasonably well for FTDX101. It's a pity Yaesu hasn't documented the scales properly. Maybe it's worth asking them though!

**Comment by mikaelnousiainen** [comment]
@mdblack98 One more question about rig implementations: are set_rit / set_xit really supposed to *enable* RIT/XIT functions too? Most rigs have a separate setting to enable/disable RIT/XIT and have possibility to set the frequency offset separately...

The reason why I'm asking is that at least the Icoms don't do this and the Yaesus seem to suffer from automatic enabling of RIT/XIT, because the offset is shared between RIT and XIT so behaviour may be a bit unpredictable at times.

I'd opt to simply remove automatic enabling of RIT/XIT when setting the frequency offset -- just like Icoms do.

**Comment by mdblack98** [comment]
You can always ask....
 

    On Friday, October 23, 2020, 02:59:41 PM CDT, Mikael Nousiainen <notifications@github.com> wrote:  
 
 


Yeah, the FT-991 S-meter seems to work at least reasonably well for FTDX101. It's a pity Yaesu hasn't documented the scales properly. Maybe it's worth asking them though!

**Comment by mdblack98** [comment]
Yes...Yaesu rigs assume if you set rit/xit != 0 you must want it on.
Hamlib doesn't turn it on....the rigs do.
Mike

 

    On Friday, October 23, 2020, 03:04:47 PM CDT, Mikael Nousiainen <notifications@github.com> wrote:  
 
 


@mdblack98 One more question about rig implementations: are set_rit / set_xit really supposed to enable RIT/XIT functions too? Most rigs have a separate setting to enable/disable RIT/XIT and have possibility to set the frequency offset separately...

The reason why I'm asking is that at least the Icoms don't do this and the Yaesus seem to suffer from automatic enabling of RIT/XIT, because the offset is shared between RIT and XIT so behaviour may be a bit unpredictable at times.

I'd opt to simply remove automatic enabling of RIT/XIT when setting the frequency offset -- just like Icoms do.

**Comment by mikaelnousiainen** [comment]
Actually there were commands `RT1` and `XT1` in the `set_rit` / `set_xit` functions that did this. I removed them and now it works logically with user being in control of whether RIT/XIT is actually enabled. I'll be doing some final testing and pushing out a PR tomorrow or on Monday.

**Comment by mdblack98** [comment]
Hmmm..that's been there since 2008 when get/set_rit was implemented.  I hope nobody is relying on that behavior.
I agree the behavior should be consistent across rigs so go for it.

**Comment by mikaelnousiainen** [comment]
Fixed in PR #426

**Comment by mikaelnousiainen** [comment]
@mdblack98 Just leaving a note here. I asked Yaesu for more details about the RM (read meter) CAT command return values and got the following answer: "Thank you for your interest in Yaesu radio products.  Our radio's CAT manual contains the CAT information that  Yaesu engineers are  comfortable publishing." :( I really wonder why they don't wish to publish this info. Icom manuals do have all of it, after all.

**Comment by N0NB** [comment]
The cynical side of me thinks that they'd only share such information to
authors of closed source software for a price.

Of course, there is always the "void the warranty" argument.  :-/

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: https://www.n0nb.us
Projects: https://github.com/N0NB
GPG fingerprint: 82D6 4F6B 0E67 CD41 F689 BBA6 FB2C 5130 D55A 8819

**Comment by mdblack98** [comment]
It can also mean they don't calibrate it so it varies with serial number.
SWR being a big inaccuracy problem with most all non-SDR rigs for example.
