### ISSUE TITLE
Yaesu FT-450D RF power reported/set wrong

### ISSUE THREAD

**Issue by bagel99** [Hamlib/Hamlib#43]
Yaesu chose to change the way the PC command works.  On the FT-450 the range is 000-255. 
On the FT-450D the range is 005-100 (the actual power in watts).  There may be other changes,
but I haven't found any yet.

The two rigs can be distinguished by what the ID command returns:
  FT-450:  0241
  FT-450D: 0244

Question: Should we create an entirely new rig for the 450D, or
should we just check which is which in newcat.c and handle the quirk there?

Brian W9BGL

**Comment by N0NB** [comment]
If that is the only difference you can find, then it's reasonable to handle in the backend after checking the ID.

**Comment by mdblack98** [comment]
Fixed
