### ISSUE TITLE
Comm failure, TS-870S

### ISSUE THREAD

**Issue by ehidle** [Hamlib/Hamlib#452]
I recently lost the ability to control my TS-870 after an ubuntu update (which updated hamlib to 3.1). I observed that I could talk to the rig with minicom and it would respond to CAT commands. But, fldigi and flrig would not communicate with the radio. I invoked rigcat from the command line and kept getting a Protocol Error message:

ehidle@**redacted**:~/software/hamlib-3.3$ rigctl -r /dev/ttyUSB2 -m 210 -D 19200
rig_open: error = Protocol error 

The "CTRL" indicator in the radio's display does illuminate when trying to communicate with hamlib. 

One other thing I noticed was that sometimes when I started minicom, I would see a string of commands load up the terminal as soon as it was opened, as if hamlib had tried to send them to the serial port but for some reason the serial port was not accepting them. That doesn't happen every time but I noticed it once or twice while trying to debug this.

Hamlib is working fine for all of my other radios (TS-590S, TS-590SG, TS-790A, TS-950SDX). I compiled 3.3 from source and the problem persists.

**Comment by mdblack98** [comment]
Please upgrade to the current hamlib.  3.3 is no longer receiving patches.
https://github.com/Hamlib/Hamlib

Mike W9MDB

 

    On Sunday, November 29, 2020, 09:33:09 AM CST, ehidle <notifications@github.com> wrote:  
 
 


I recently lost the ability to control my TS-870 after an ubuntu update (which updated hamlib to 3.1). I observed that I could talk to the rig with minicom and it would respond to CAT commands. But, fldigi and flrig would not communicate with the radio. I invoked rigcat from the command line and kept getting a Protocol Error message:

ehidle@redacted:~/software/hamlib-3.3$ rigctl -r /dev/ttyUSB2 -m 210 -D 19200
rig_open: error = Protocol error

One other thing I noticed was that sometimes when I started minicom, I would see a string of commands load up the terminal as soon as it was opened, as if hamlib had tried to send them to the serial port but for some reason the serial port was not accepting them. That doesn't happen every time but I noticed it once or twice while trying to debug this.

Hamlib is working fine for all of my other radios (TS-590S, TS-590SG, TS-790A, TS-950SDX).

**Comment by ehidle** [comment]
> Please upgrade to the current hamlib.  3.3 is no longer receiving patches. https://github.com/Hamlib/Hamlib Mike W9MDB 

Done. Pulled from git and rebuilt, and the problem persists:

ehidle@**redacted**:~/software/Hamlib$ rigctl -r /dev/ttyUSB2 -m 2010 -s 19200
rig_open: error = Protocol error

**Comment by mdblack98** [comment]
rigctl -r /dev/ttyUSB2 -m 2010 -s 19200 -vvvvv -Z >&debug.txt

And send me the debug.txt
Mike

 

    On Sunday, November 29, 2020, 10:03:22 AM CST, ehidle <notifications@github.com> wrote:  
 
 



Please upgrade to the current hamlib.  3.3 is no longer receiving patches. https://github.com/Hamlib/Hamlib Mike W9MDB


Done. Pulled from git and rebuilt, and the problem persists:

ehidle@redacted:~/software/Hamlib$ rigctl -r /dev/ttyUSB2 -m 2010 -s 19200
rig_open: error = Protocol error

**Comment by ehidle** [comment]
Ooohhhhh this is interesting. I figured it out: 

ehidle@**redacted**:~$ rigctl -m 2010 -r /dev/ttyUSB2 -s 19200 -vvvvv
rigctl Hamlib 4.1~git
Last commit was Sun Nov 29 04:34:15 2020 +0000 SHA=d782fd
Report bugs to <hamlib-developer@lists.sourceforge.net>

rig_init called
initrigs4_kenwood called
rig_register called
rig_register: rig_register (2012)
rig_register called
rig_register: rig_register (2013)
rig_register called
rig_register: rig_register (2001)
rig_register called
rig_register: rig_register (2025)
rig_register called
rig_register: rig_register (2003)
rig_register called
rig_register: rig_register (2004)
rig_register called
rig_register: rig_register (2016)
rig_register called
rig_register: rig_register (2024)
rig_register called
rig_register: rig_register (2005)
rig_register called
rig_register: rig_register (2007)
rig_register called
rig_register: rig_register (2009)
rig_register called
rig_register: rig_register (2010)
rig_register called
rig_register: rig_register (2022)
rig_register called
rig_register: rig_register (2014)
rig_register called
rig_register: rig_register (2030)
rig_register called
rig_register: rig_register (2021)
rig_register called
rig_register: rig_register (2029)
rig_register called
rig_register: rig_register (2043)
rig_register called
rig_register: rig_register (2044)
rig_register called
rig_register: rig_register (2045)
rig_register called
rig_register: rig_register (2047)
rig_register called
rig_register: rig_register (2038)
rig_register called
rig_register: rig_register (2002)
rig_register called
rig_register: rig_register (2011)
rig_register called
rig_register: rig_register (2006)
rig_register called
rig_register: rig_register (2008)
rig_register called
rig_register: rig_register (2015)
rig_register called
rig_register: rig_register (2026)
rig_register called
rig_register: rig_register (2017)
rig_register called
rig_register: rig_register (2033)
rig_register called
rig_register: rig_register (2042)
rig_register called
rig_register: rig_register (2020)
rig_register called
rig_register: rig_register (2023)
rig_register called
rig_register: rig_register (2027)
rig_register called
rig_register: rig_register (2034)
rig_register called
rig_register: rig_register (2031)
rig_register called
rig_register: rig_register (2039)
rig_register called
rig_register: rig_register (2037)
rig_register called
rig_register: rig_register (2028)
rig_register called
rig_register: rig_register (2019)
rig_register called
rig_register: rig_register (2032)
rig_register called
rig_register: rig_register (2036)
rig_register called
rig_register: rig_register (2048)
rig_register called
rig_register: rig_register (2040)
rig_register called
rig_register: rig_register (2041)
rig_register called
rig_register: rig_register (2046)
kenwood_init called, version 20201126/20201126.0
kenwood_init: if_len = 37
rig_open called
port_open called
serial_open called
serial_setup called
serial_setup: tcgetattr
serial_setup: cfmakeraw
serial_setup: cfsetispeed=19200,0x000e
serial_setup: cfsetospeed=19200,0x000e
serial_setup: data_bits=8
serial_setup: parity=0
serial_setup: tcsetattr TCSANOW
serial_flush called
tcflush
kenwood_open called
kenwood_get_id called
kenwood_transaction called
kenwood_transaction: cmdstr = ID
rig_flush: called for serial device
serial_flush called
tcflush
write_block called
write_block(): TX 3 bytes
0000    49 44 3b                                            ID;             
read_string called, rxmax=128
read_string(): RX 7 characters
0000    31 33 36 34 31 30 3b                                136410;         
kenwood_transaction: read_string(len=7)='136410;'
kenwood_transaction: wrong reply 13 for command ID
kenwood_transaction: retry_read=0, rs->rigport.retry=0
kenwood_transaction: returning retval=-8
kenwood_open: no response to get_id from rig...continuing anyways.
kenwood_open: cannot get identification
rig_open: error = Protocol error 

So this is strange. "136410" is the last 6 of current VFO reading at the time I invoked rigctl. If I run it again, it seems to work. So this is an fldigi config problem. Here's the fldigi log followed immediately by two attempts to run rigctl directly. What I failed to notice is that the update also upgraded fldigi, which did not preserve all of my settings for the radio control config (the DTR high setting, which should be default for this radio). I've been chasing a red herring.. 

ehidle@**redacted**:~/.fldigi$ fldigi
V: [11:34:54] rigcontrol/ptt.cxx : 132 : set
    PTT via UNKNOWN : OFF
D: [11:34:54] rigcontrol/serial.cxx : 213 : SetPTT
    PTT fd < 0
V: [11:34:54] rigcontrol/ptt.cxx : 132 : set
    PTT via NONE : OFF
D: [11:34:54] rigcontrol/serial.cxx : 213 : SetPTT
    PTT fd < 0
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
I: [11:34:55] rigcontrol/rigclass.cxx : 63 : init
    Initialised rig model 210: TS-870S
I: [11:34:55] rigcontrol/rigclass.cxx : 219 : setConf
    setting "rig_pathname" to "/dev/ttyUSB2"
I: [11:34:55] rigcontrol/rigclass.cxx : 219 : setConf
    setting "post_write_delay" to "0"
I: [11:34:55] rigcontrol/rigclass.cxx : 219 : setConf
    setting "write_delay" to "0"
I: [11:34:55] rigcontrol/rigclass.cxx : 219 : setConf
    setting "timeout" to "200"
I: [11:34:55] rigcontrol/rigclass.cxx : 219 : setConf
    setting "retry" to "10"
I: [11:34:55] rigcontrol/rigclass.cxx : 219 : setConf
    setting "serial_speed" to "19200"
**I: [11:34:55] rigcontrol/rigclass.cxx : 219 : setConf
    setting "dtr_state" to "OFF"**
I: [11:34:55] rigcontrol/rigclass.cxx : 219 : setConf
    setting "serial_handshake" to "Hardware"
I: [11:34:55] rigcontrol/rigclass.cxx : 219 : setConf
    setting "stop_bits" to "1"
**E: [11:34:59] rigcontrol/hamlib.cxx : 88 : show_error
    hamlib_init: Communication timed out**
D: [11:34:59] rigcontrol/rigsupport.cxx : 540 : init_NoRig_RigDialog
    no rig
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    # rfcarrier rig_mode carrier mode usage
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    1000500 USB 800 CW 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    1807000 USB 1000 BPSK31 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    3505000 USB 800 CW 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    3580000 USB 1000 BPSK31 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    7005000 USB 800 CW 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    7030000 USB 1000 BPSK31 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    7070000 USB 1000 BPSK31 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    10135000 USB 1000 BPSK31 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    14005000 USB 800 CW 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    14070000 USB 1000 BPSK31 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    18100000 USB 1000 BPSK31 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    21005000 USB 800 CW 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    21070000 USB 1000 BPSK31 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    24920000 USB 1000 BPSK31 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    28005000 USB 800 CW 
I: [11:34:59] rigcontrol/rigsupport.cxx : 251 : readFreqList
    28120000 USB 1000 BPSK31 
V: [11:34:59] rigcontrol/ptt.cxx : 132 : set
    PTT via NONE : OFF
D: [11:34:59] rigcontrol/serial.cxx : 213 : SetPTT
    PTT fd < 0
V: [11:34:59] rigcontrol/ptt.cxx : 132 : set
    PTT via HAMLIB : OFF
ehidle@**redacted**:~/.fldigi$ rigctl -r /dev/ttyUSB2 -m 2010 -s 19200
rig_open: error = Protocol error 
ehidle@**redacted**:~/.fldigi$ rigctl -r /dev/ttyUSB2 -m 2010 -s 19200

Rig command: 

Thanks for the prodding. At least I got hamlib updated to git out of it :)

**Comment by mdblack98** [comment]
So nothing to fix.
