### ISSUE TITLE
IC-7100 memory bank selection

### ISSUE THREAD

**Issue by wb4bxo** [Hamlib/Hamlib#475]
Memory bank selection not working for IC-7100. Returns as not supported but the 7100 has 5 banks like the 7000

**Comment by wb4bxo** [comment]
Actually I just pulled down the repo and added the banks for the IC-7100. But for some reason all my rig numbers changed for the build. When I figure that out I'll send you a pull request with this added. 
Thanks.

**Comment by mdblack98** [comment]
Rig numbers did all change a while ago to support more models per manufacturer.
Mike W9MDB

 

    On Monday, December 21, 2020, 10:15:05 PM CST, wb4bxo <notifications@github.com> wrote:  
 
 


Actually I just pulled down the repo and added the banks for the IC-7100. But for some reason all my rig numbers changed for the build. When I figure that out I'll send you a pull request with this added.
Thanks.
