### ISSUE TITLE
Hamlib 4.0 won't configure python bindings on os/x

### ISSUE THREAD

**Issue by billshine** [Hamlib/Hamlib#477]
configure: WARNING: libnova support not found, required by INDI.
checking whether to build HTML rig feature matrix... check
checking gd.h usability... no
checking gd.h presence... no
checking for gd.h... no
checking whether to build rigmem XML support... no
checking whether to build USRP backend... no
checking whether to build C++ binding... yes
checking whether to build perl binding... no
checking whether to build python binding... yes
checking for python3.9... /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
checking for a version of Python >= '2.1.0'... yes
checking for the distutils Python package... yes
checking for Python include path... -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9
checking for Python library path... -L/Library/Frameworks/Python.framework/Versions/3.9/lib -lpython3.9
checking for Python site-packages path... /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
checking python extra libraries... -ldl   -framework CoreFoundation 
checking python extra linking flags... -Wl,-stack_size,1000000  -framework CoreFoundation Python.framework/Versions/3.9/Python
checking consistency of all components of python development environment... no
configure: error: in `/Users/bill/hamlib/hamlib':
configure: error: 
  Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LIBS environment variable.
  Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
  ============================================================================
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================

The problem is that the extra linking flags is incorrect.   -framework CoreFoundation is o.k., but we need a "-framework" in front of Python.framework ... Someone has to put it there, and python gives us the wrong answer....

After fixing this, the link command is wrong (probably because you are using a ridiculous libtool script to do the link, which fails, beacuse it doesn not reference the python library (/Library/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib ...   Wouldn't it be much simpler to just use cmake, and drop autoconfigure and libtool?

**Comment by mdblack98** [comment]
Build works on python 3.8.5 but not on python 2.7
distutils is being deprecated so have to figure out how to split the config for python2 and python3
