### ISSUE TITLE
Hamlib PTT error: communication bus collision.

### ISSUE THREAD

**Issue by Supermagnum** [Hamlib/Hamlib#489]
Hello, when trying to use both FreeDV and Flrig together, I get a Hamlib PTT error: communication bus collision.
I am using Linux Mint 20 and a FT-991 .

Relevant links:
https://github.com/drowe67/freedv-gui/issues/62

https://www.reddit.com/r/linuxmint/comments/ixfs7d/hamlib_communication_collision_using_freedv_and/?utm_medium=android_app&utm_source=share

**Comment by mdblack98** [comment]
Hamlib ptt sharing was made optional a couple months ago.

If you want to use Hamlib PTT from FreeDV you should use Rig Model "Hamlib NET rigctl".
And run "rigctld" to talk to your rig with the option "--set-conf=ptt_share=1"

Then FreeDV and Hamllib can share the PTT port.

You should be able to run FreeDV
Flrig
FreeDV talking to rigctld
rigctld talking to FLRig
In this setup WSJT-X could connect to hamlib or FLRig.

You can also do
FLRig
FreeDV talking to FLRig
WSJT-X talking to FLRig
