### ISSUE TITLE
Yaesu stop bits change to 2

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#511]
It appears all Yaesu rigs should be using 2 stop bits.
Comments in code said 1 stop bit was "assumed" so we're changing the assumption to 2 stop bits.

**Comment by mikaelnousiainen** [comment]
@mdblack98 I wonder how did the CAT commands still were functioning properly with 1 stop bit? Is there official documentation for this?

**Comment by mdblack98** [comment]
It's a crap shoot....will frequently work with 1 stop bit.
Bill was testing an FT2000 over a remote serial port and getting a lot of retries until he changed to 2 stop bits on the whole serial chain.
Mike

 

    On Sunday, January 17, 2021, 10:44:05 AM CST, Mikael Nousiainen <notifications@github.com> wrote:  
 
 


@mdblack98 I wonder how did the CAT commands still were functioning properly with 1 stop bit? Is there official documentation for this?

**Comment by mikaelnousiainen** [comment]
@mdblack98 That's interesting, great that you were able to figure this out. I'll have to test this with an FT-991, as all commands have been very slow to execute on that rig.

**Comment by mdblack98** [comment]
If it's still slow please send a debug log.
The retries might explain the slowness...
Mike

 

    On Sunday, January 17, 2021, 10:57:28 AM CST, Mikael Nousiainen <notifications@github.com> wrote:  
 
 


@mdblack98 That's interesting, great that you were able to figure this out. I'll have to test this with an FT-991, as all commands have been very slow to execute on that rig.
