### ISSUE TITLE
yaesu ft757gx patch by mike black

### ISSUE THREAD

**Issue by stillcool40** [Hamlib/Hamlib#53]
im no programmer, i just want to get wsjt working with the ft757gx.

i see the patch by mike but i have totally NO IDEA what to do with it or how to use it.

can anyone help with DUMMY instructions?

I tried following the install guide and it just didnt work.

**Comment by mdblack98** [comment]
Are you compiling hamlib?
If so, save the patch and do this from the hamlib directory (please download the patch again as I had too much in it)

git patch pathtofilename


 de MIke W9MDB

    On Thursday, September 27, 2018, 12:44:48 PM CDT, stillcool40 <notifications@github.com> wrote:  
 
 
im no programmer, i just want to get wsjt working with the ft757gx.

i see the patch by mike but i have totally NO IDEA what to do with it or how to use it.

can anyone help with DUMMY instructions?

I tried following the install guide and it just didnt work.

**Comment by mdblack98** [comment]
Fixed
