### ISSUE TITLE
DLL build

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#542]
See if we can build the DLLs for Windows when --enable-shared is used during configure
Of possible use https://www.transmissionzero.co.uk/computing/building-dlls-with-mingw/

**Comment by gvanem** [comment]
I do link a `Hamlib.DLL` for MinGW, MSVC and clang-cl in my modified fork of Hamlib: 
https://github.com/gvanem/Hamlib/blob/master/Makefile.Windows#L1025

(with a GNU-make macro, and no configure stuff).

**Comment by mdblack98** [comment]
How do you generate the Makefile.Windows file?

Mike

 

    On Thursday, February 25, 2021, 03:11:51 AM CST, Gisle Vanem <notifications@github.com> wrote:  
 
 


I do link a Hamlib.DLL for MinGW, MSVC and clang-cl in my modified fork of Hamlib:
https://github.com/gvanem/Hamlib/blob/master/Makefile.Windows#L1025

(with a GNU-make macro, and no configure stuff).

**Comment by gvanem** [comment]
Sick of autotools. I hand-made it for own use.
