### ISSUE TITLE
FTdx101D intermittently Sub mode reported for Main

### ISSUE THREAD

**Issue by Ian-G3VPX** [Hamlib/Hamlib#606]
Running piWebCAT:  Main: LSB  3000Hz    Sub CW-U 1400Hz
Main selected. 
    piWebaCAT configured to do a \get_mode Main and a \get_mode Sub every 1-2 seconds

I observe:  LSB button illuminated - but flips to CW and back every 2 seconds or so

I cannot reproduce this with telnet, but after much trying to prove otherwise
I think it is in rigctld
Reason for this:    String read from socket as: "CW\n3000\n"
                                  I can't be generating this?  CW is Sub mode.  3000 is Main BW.
Form web browser inspect element > network listing I see:

\get_mode Sub   >   CW\n1400\n        = ok        Sub mode and Sub BW
\get_mode Main   >  CW\n3000\n       = wrong  Sub mode and Main BW
\get_mode Sub   >  CW\n1400\n         =ok          Sub mode and Sub BW
\get_mode Sub   >  CW\n1400\n         = ok         Sub mode and Sub BW
\get_mode Main   >  CW\n3000\n       = wrong    Sub mode and Main BW
\get_mode Main   >  LSB\n3000\n       = ok   ..      Main mode and Main BW
\get_mode Sub   >  CW\n1400\n         = ok           Sub mode and Sub BW

If I then select Sub, all is well. The reverse scenario doesn't happen.

If I switch off the background check of \get_mode Sub
then \get_mode Main behaves correctly

[FTdx101D_power_telnet.txt](https://github.com/Hamlib/Hamlib/files/6131928/FTdx101D_power_telnet.txt)

Ian
G3VPX

**Comment by mdblack98** [comment]
This is due to the cache logic not covering this situation.
Need to finish up the new caching logic.
