### ISSUE TITLE
Hamlib error: IO error while opening connection to rig

### ISSUE THREAD

**Issue by kb3mkd** [Hamlib/Hamlib#609]
I have been using my IC-7410 wtih hamlib for digital modes for some time. Yesterday I used my rig on ssb, switching the data and data off mode to mic,acc. Today i switched it back to USB and tried to use the system as normal, but get the error above. 
The only changes I made were the 2 changes in the rig, and changing them back should have gone back the way it was, I would think.
Using Linux Mint.

**Comment by mdblack98** [comment]
Can you provide some debug info?  Using -vvvvv?
Aer you running rigctl or some app with hamlib built in?

**Comment by kb3mkd** [comment]
wsjtx

**Comment by mdblack98** [comment]
What operating system?
Mike W9MDB

 

    On Monday, March 15, 2021, 04:52:11 PM CDT, kb3mkd ***@***.***> wrote:  
 
 


wsjtx

**Comment by mdblack98** [comment]
What version of WSTJ-X too please?

 

    On Monday, March 15, 2021, 04:52:11 PM CDT, kb3mkd ***@***.***> wrote:  
 
 


wsjtx

**Comment by kb3mkd** [comment]
v2.1.0

**Comment by kb3mkd** [comment]
I mentioned in my original post Linux Mint

**Comment by mdblack98** [comment]
I just noticed the Linux Mint.
Please provide 
rigctl -m 3067 -r /dev/ttyUSB0 -s 19200 -vvvvv -Z f >&log.txt
And send the log.txt file 
Mike W9MDB
 

    On Monday, March 15, 2021, 04:55:28 PM CDT, Michael Black ***@***.***> wrote:  
 
 

What version of WSTJ-X too please?

 

 On Monday, March 15, 2021, 04:52:11 PM CDT, kb3mkd ***@***.***> wrote: 
 
 


wsjtx

**Comment by kb3mkd** [comment]
rigctl: invalid option -- 'Z'
And then a bunch of usage info The version is the wsjtx version 2.1.0
Hamlib version is coming up as 3.1-7build1

**Comment by mdblack98** [comment]
Please upgrade wsjt-x and hamlib -- both of those versions are no longer supported.
Mike W9MDB

 

    On Monday, March 15, 2021, 05:03:47 PM CDT, kb3mkd ***@***.***> wrote:  
 
 


rigctl: invalid option -- 'Z'
And then a bunch of usage info The version is the wsjtx version 2.1.0
Hamlib version is coming up as 3.1-7build1

**Comment by kb3mkd** [comment]
Is there a repository I can get these from or must I recompile?

**Comment by mdblack98** [comment]
It would appear the .deb package is what you want
https://www.physics.princeton.edu/pulsar/k1jt/wsjtx.html

Mike W9MDB

 

    On Monday, March 15, 2021, 05:11:13 PM CDT, kb3mkd ***@***.***> wrote:  
 
 


Is there a repository I can get these from or must I recompile?

**Comment by kb3mkd** [comment]
Thanks Mike!
