### ISSUE TITLE
newly upgraded system still won't connect.

### ISSUE THREAD

**Issue by kb3mkd** [Hamlib/Hamlib#613]
WSJT-X v2.3.0
Linux Mint 20
Hamlib 3.3-10build1
Getting a rig failure. IO error
Settings serial port /dev/tty/USB0
8-N-1
PTT method CAT
Mode USB
Split rig

**Comment by mdblack98** [comment]
Please upgrade hamlib to at least 4.1Seems
Mike W9MDB

 

    On Tuesday, March 16, 2021, 04:14:44 PM CDT, kb3mkd ***@***.***> wrote:  
 
 


WSJT-X v2.3.0
Linux Mint 20
Hamlib 3.3-10build1
Getting a rig failure. IO error
Settings serial port /dev/tty/USB0
8-N-1
PTT method CAT
Mode USB
Split rig

**Comment by kb3mkd** [comment]
Is there a debian / ubuntu / mint repository or do I have to compile it?

**Comment by kb3mkd** [comment]
I tried compiling it, I get 
Hamlib error:                                                                         IO error
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             rig.c(745):rig_open return

**Comment by mdblack98** [comment]
Are you sure you have access to the port?  Try as root....
