### ISSUE TITLE
LIBUSB problem

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#634]
it looks like the above commit causes critical libusb code to be #ifdef
excluded, I am seeing this on MS Windows MinGW builds. The configuration
macro HAVE_LIBUSB_H is being used and that is not defined, perhaps
HAVE_LIBUSB_1_0_LIBUSB_H should have been used? Offending code is at
src/iofunc.c lines 149 and 206. Also src/rotator.c lines 64, 421, and 533.

73
Bill
G4WJS.

**Comment by mdblack98** [comment]
I take you don't see any LIBUSB defined in include/config.h ?
Mike W9MDB

 

    On Saturday, March 27, 2021, 02:44:41 PM CDT, Michael Black ***@***.***> wrote:  
 
 


it looks like the above commit causes critical libusb code to be #ifdef
excluded, I am seeing this on MS Windows MinGW builds. The configuration
macro HAVE_LIBUSB_H is being used and that is not defined, perhaps
HAVE_LIBUSB_1_0_LIBUSB_H should have been used? Offending code is at
src/iofunc.c lines 149 and 206. Also src/rotator.c lines 64, 421, and 533.

73
Bill
G4WJS.

**Comment by g4wjs** [comment]
> I take you don't see any LIBUSB defined in include/config.h ? Mike W9MDB

/* Define if libusb-1.0 is available */
#define HAVE_LIBUSB 1

/* Define to 1 if you have the <libusb-1.0/libusb.h> header file. */
#define HAVE_LIBUSB_1_0_LIBUSB_H 1

/* Define to 1 if you have the <libusb.h> header file. */
/* #undef HAVE_LIBUSB_H */

73
Bill
G4WJS.

**Comment by mdblack98** [comment]
Hopefully fixed in my latest patch.
Mike

 

    On Saturday, March 27, 2021, 03:40:43 PM CDT, Bill Somerville ***@***.***> wrote:  
 
 



I take you don't see any LIBUSB defined in include/config.h ? Mike W9MDB


/* Define if libusb-1.0 is available */
#define HAVE_LIBUSB 1

/* Define to 1 if you have the <libusb-1.0/libusb.h> header file. */
#define HAVE_LIBUSB_1_0_LIBUSB_H 1

/* Define to 1 if you have the <libusb.h> header file. /
/ #undef HAVE_LIBUSB_H */

73
Bill
G4WJS.
