### ISSUE TITLE
FTdx101D RFPOWER_METER_WATTS returns zero

### ISSUE THREAD

**Issue by Ian-G3VPX** [Hamlib/Hamlib#641]
Log attached - rigctld running in RPi terminal.
Telnet running in second terminal
single command entered after startup:
l Main RFPOWER_METER_WATTS
returns zero  (rig was transmitting CW 90w
Ian
G3VPX
[Ftdx101D_RFPOWER_log.txt](https://github.com/Hamlib/Hamlib/files/6236281/Ftdx101D_RFPOWER_log.txt)

**Comment by mdblack98** [comment]
Do you have a choice which side the power meter is on?
Mike

 

    On Wednesday, March 31, 2021, 06:42:11 AM CDT, Ian-G3VPX ***@***.***> wrote:  
 
 


Log attached - rigctld running in RPi terminal.
Telnet running in second terminal
single command entered after startup:
l Main RFPOWER_METER_WATTS
returns zero (rig was transmitting CW 90w
Ian
G3VPX
Ftdx101D_RFPOWER_log.txt
