### ISSUE TITLE
hamlib4 borked for FT897D

### ISSUE THREAD

**Issue by edwar64896** [Hamlib/Hamlib#696]
I"m trying to put together a new AR computer based on ubuntu. 
CQRLOG depends on hamlib4 packages which are broken when attempting to connect to the FT897D
Because of fundamental changes to the way hamlib works when referencing rigs, there is no backwards compatibility and thus no way to get this to work unless the packages can be updated and released.

Package version is currently libhamlib4 v 4.0-4

I can't find a workaround for this at all at the present time.

**Comment by mdblack98** [comment]
Please try the current master and see if it works.
You can download a tar file from here and compile it.
http://n0nb.users.sourceforge.net/

Mike

**Comment by edwar64896** [comment]
doing it now. Just a bit concerned it's going to stuff up package dependencies if I overlay a hand-built lib

**Comment by mdblack98** [comment]
Just uninstall the package
When building hamlib use./configure --prefix=/usr
That will install hamlib in the same place as the package
Then, if you want to install a package again it will overwrite it.
Mike W9MDB

 

    On Sunday, May 9, 2021, 10:43:29 PM CDT, edwar64896 ***@***.***> wrote:  
 
 


doing it now. Just a bit concerned it's going to stuff up package dependencies if I overlay a hand-built lib

**Comment by edwar64896** [comment]
ok compiles cleanly, but errors out on startup.

> rigctld: symbol lookup error: rigctld: undefined symbol: debugmsgsave

**Comment by edwar64896** [comment]
ok fixed. still a lurking  copy of the packaved libhamlib in /lib/x86_64-linux-gnu

deleted this and it now finds the right one.

**Comment by edwar64896** [comment]
JTDX 2.2.156 
Hamlib error: Invalid parameter while exchanging VFOs
rig_get_vfo: no get_vfo
Opened rig model 1023, 'FT-897'
rigctl_set_rit: chkarg err
handle_socket: rigctl_parse retcode=-1
handle_socket: rigctl_parse retcode=1

please forgive the question, but is this not backwards compatible for rigctl NET connections?

**Comment by mdblack98** [comment]
Is that with CQRLog running?
Trying to figure out who's calling rigctl_set_rit -- JTDX doesn't do that.
And whoever is calling it is doing it incorrectly.



 

    On Sunday, May 9, 2021, 11:17:41 PM CDT, edwar64896 ***@***.***> wrote:  
 
 


JTDX 2.2.156
Hamlib error: Invalid parameter while exchanging VFOs
rig_get_vfo: no get_vfo
Opened rig model 1023, 'FT-897'
rigctl_set_rit: chkarg err
handle_socket: rigctl_parse retcode=-1
handle_socket: rigctl_parse retcode=1

please forgive the question, but is this not backwards compatible for rigctl NET connections?

**Comment by mdblack98** [comment]
Seems this was fixed by upgrading.
