### ISSUE TITLE
not reachable label.

### ISSUE THREAD

**Issue by ihsinme** [Hamlib/Hamlib#723]
good day.
I may be wrong, but judging by the code, this `case` is not reachable.
https://github.com/Hamlib/Hamlib/blob/c7b10e0e8fafa0736670393524da5f0270ed7c4a/rigs/yaesu/ft767gx.c#L1199
range `tx_vfo` `[1..2] `

**Comment by mdblack98** [comment]
VFO_CURR is a special case and will not be listed in any rig capabilities.
