### ISSUE TITLE
Allow using two separate rotator models for Az/El

### ISSUE THREAD

**Issue by mikaelnousiainen** [Hamlib/Hamlib#758]
This is a bit related to #747, where a Green Heron rotator controller has separate serial ports for Az and El control. In addition to this, I think Hamlib could provide an abstraction over two completely separate rotators/models where one of them would control azimuth and another elevation. Basically most (all?) Hamlib client software seems to assume that a single rotator handles both azimuth and elevation rotation, so if one has two separate rotators and separate controllers for both azimuth and elevation, using them as one unit is not easy (or possible at all).

**Comment by mdblack98** [comment]
Nobody has ever asked for this.  That's not your situation, is it?
I'm not inclined to implement something that would never be used.
