### ISSUE TITLE
rigctl Option prompt displaying when not needed

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#773]
Rig command: Y 1 0
Option:

Only on Windows due to non-use of readline
Able to duplicate on Unix with --without-readline

**Comment by mdblack98** [comment]
I may have accidentally put some old fixes in the 4.3.1 list.  For some reason I had them tagged for 4.4.
Mike

 

    On Monday, September 13, 2021, 03:36:58 AM CDT, Nate Bargmann ***@***.***> wrote:  
 
 


Looks like all of these changes already exist in 4.3.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by N0NB** [comment]
* On 2021 13 Sep 04:42 -0500, Michael Black wrote:
> I may have accidentally put some old fixes in the 4.3.1 list.  For
> some reason I had them tagged for 4.4.

That's fine.  Git lets me know when there is an issue and I'll just note
in each issue if any were applied.

73, Nate

-- 
"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."
Web: https://www.n0nb.us
Projects: https://github.com/N0NB
GPG fingerprint: 82D6 4F6B 0E67 CD41 F689 BBA6 FB2C 5130 D55A 8819
