### ISSUE TITLE
FreeDV with TS-890 always selects VFOA with hamlib 4.3, VFOB usable with hamlib 4.2

### ISSUE THREAD

**Issue by Tyrbiter** [Hamlib/Hamlib#781]
I built my own rpms on Fedora 34 using the hamlib-4.3 source tarballs. Installed them and appear to be working.

FreeDV is used with a Kenwood TS-890

Using freedv, if I have VFOA selected everything works as before, however if I have VFOB selected using the radio front panel controls then the next time the freedv start or tx button is pressed the radio switches to VFOA.

Unsure if it is relevant, but initially with new hamlib the PTT config changed from TS-890 to TS-870S, I had to change it back.

Here is the freedv debug output with hamlib 4.3, I have chopped out all the ALSA debug as it isn't relevant:

rig_init: rig has VFO_A
rig_init: rig has VFO_B
kenwood_init called, version 20210829/20210829.1
kenwood.c(738):kenwood_init return(0)
rig.c(684):rig_open entered
iofunc.c(68):port_open entered
serial.c(144):serial_open entered
serial_open: /dev/ttyUSB1
serial.c(291):serial_setup entered
serial.c(631):serial_setup return(0)
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
serial.c(266):serial_open return(0)
iofunc.c(186):port_open return(0)
rig.c(220):add_opened_rig return(0)
kenwood_open called
kenwood_get_id called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(1029):kenwood_get_id return(0)
rig.c(5589):rig_get_powerstat entered
kenwood_get_powerstat called
kenwood_safe_transaction called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(647):kenwood_safe_transaction return(0)
kenwood.c(4529):kenwood_get_powerstat return(0)
rig.c(5608):rig_get_powerstat return(0)
kenwood_open: found the right driver for TS-890S(2041)
kenwood_get_trn called
kenwood_safe_transaction called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(647):kenwood_safe_transaction return(0)
kenwood.c(4456):kenwood_get_trn return(0)
kenwood_get_split_vfo_if called
kenwood_get_if called
kenwood_safe_transaction called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(647):kenwood_safe_transaction return(0)
kenwood_get_split_vfo_if: priv->tx_vfo=VFOA
kenwood.c(1483):kenwood_get_split_vfo_if return(0)
kenwood_open: priv->tx_vfo=VFOA
rig.c(2616):rig_set_vfo entered
rig_set_vfo called vfo=VFOA
kenwood_set_vfo called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(1163):kenwood_set_vfo return(0)
kenwood_get_freq called
kenwood_safe_transaction called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(647):kenwood_safe_transaction return(0)
kenwood.c(1760):kenwood_get_freq return(0)
rig.c(2728):rig_set_vfo return(0)
kenwood.c(971):kenwood_open return(0)
rig.c(2753):rig_get_vfo entered
rig.c(2782):rig_get_vfo return(0)
rig.c(1102):rig_open return(0)
rig.c(2833):rig_set_ptt entered
kenwood_set_ptt called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(4304):kenwood_set_ptt return(0)
rig.c(3094):rig_set_ptt return(0)
rig.c(2833):rig_set_ptt entered
kenwood_set_ptt called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(4304):kenwood_set_ptt return(0)
rig.c(3094):rig_set_ptt return(0)
rig.c(1124):rig_close entered
iofunc.c(200):port_close entered
ser_close called
ser_close: restoring options
serial.c(844):ser_close return(0)
iofunc.c(234):port_close return(0)
rig.c(243):remove_opened_rig return(0)
rig.c(1280):rig_close return(0)
rig.c(1299):rig_cleanup entered
kenwood_cleanup called
kenwood.c(748):kenwood_cleanup return(0)
rig.c(1324):rig_cleanup return(0)
rig_init: rig has VFO_A
rig_init: rig has VFO_B
kenwood_init called, version 20210829/20210829.1
kenwood.c(738):kenwood_init return(0)
rig.c(684):rig_open entered
iofunc.c(68):port_open entered
serial.c(144):serial_open entered
serial_open: /dev/ttyUSB1
serial.c(291):serial_setup entered
serial.c(631):serial_setup return(0)
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
serial.c(266):serial_open return(0)
iofunc.c(186):port_open return(0)
rig.c(220):add_opened_rig return(0)
kenwood_open called
kenwood_get_id called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(1029):kenwood_get_id return(0)
rig.c(5589):rig_get_powerstat entered
kenwood_get_powerstat called
kenwood_safe_transaction called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(647):kenwood_safe_transaction return(0)
kenwood.c(4529):kenwood_get_powerstat return(0)
rig.c(5608):rig_get_powerstat return(0)
kenwood_open: found the right driver for TS-890S(2041)
kenwood_get_trn called
kenwood_safe_transaction called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(647):kenwood_safe_transaction return(0)
kenwood.c(4456):kenwood_get_trn return(0)
kenwood_get_split_vfo_if called
kenwood_get_if called
kenwood_safe_transaction called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(647):kenwood_safe_transaction return(0)
kenwood_get_split_vfo_if: priv->tx_vfo=VFOA
kenwood.c(1483):kenwood_get_split_vfo_if return(0)
kenwood_open: priv->tx_vfo=VFOA
rig.c(2616):rig_set_vfo entered
rig_set_vfo called vfo=VFOA
kenwood_set_vfo called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(1163):kenwood_set_vfo return(0)
kenwood_get_freq called
kenwood_safe_transaction called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(647):kenwood_safe_transaction return(0)
kenwood.c(1760):kenwood_get_freq return(0)
rig.c(2728):rig_set_vfo return(0)
kenwood.c(971):kenwood_open return(0)
rig.c(2753):rig_get_vfo entered
rig.c(2782):rig_get_vfo return(0)
rig.c(1102):rig_open return(0)
rig.c(2328):rig_get_mode entered
kenwood_get_mode called
kenwood_safe_transaction called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(647):kenwood_safe_transaction return(0)
kenwood2rmode called
kenwood.c(659):kenwood2rmode return(8)
rig.c(2455):rig_passband_normal entered
rig_passband_normal: return filter#0, width=2400
rig.c(2475):rig_passband_normal return(2400)
kenwood.c(2395):kenwood_get_mode return(0)
rig.c(1407):set_cache_mode entered
rig.c(1471):set_cache_mode return(0)
rig.c(2434):rig_get_mode return(0)
rig_get_freq(1993) called vfo=currVFO
rig.c(2002) vfo=currVFO, curr_vfo=VFOA
rig.c(2063):rig_get_freq return(0)
rig.c(2833):rig_set_ptt entered
kenwood_set_ptt called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(4304):kenwood_set_ptt return(0)
rig.c(3094):rig_set_ptt return(0)
rig.c(1124):rig_close entered
iofunc.c(200):port_close entered
ser_close called
ser_close: restoring options
serial.c(844):ser_close return(0)
iofunc.c(234):port_close return(0)
rig.c(243):remove_opened_rig return(0)
rig.c(1280):rig_close return(0)
rig.c(1299):rig_cleanup entered
kenwood_cleanup called
kenwood.c(748):kenwood_cleanup return(0)
rig.c(1324):rig_cleanup return(0)
rig_init: rig has VFO_A
rig_init: rig has VFO_B
kenwood_init called, version 20210829/20210829.1
kenwood.c(738):kenwood_init return(0)
rig.c(684):rig_open entered
iofunc.c(68):port_open entered
serial.c(144):serial_open entered
serial_open: /dev/ttyUSB1
serial.c(291):serial_setup entered
serial.c(631):serial_setup return(0)
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
serial.c(266):serial_open return(0)
iofunc.c(186):port_open return(0)
rig.c(220):add_opened_rig return(0)
kenwood_open called
kenwood_get_id called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(1029):kenwood_get_id return(0)
rig.c(5589):rig_get_powerstat entered
kenwood_get_powerstat called
kenwood_safe_transaction called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(647):kenwood_safe_transaction return(0)
kenwood.c(4529):kenwood_get_powerstat return(0)
rig.c(5608):rig_get_powerstat return(0)
kenwood_open: found the right driver for TS-890S(2041)
kenwood_get_trn called
kenwood_safe_transaction called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(647):kenwood_safe_transaction return(0)
kenwood.c(4456):kenwood_get_trn return(0)
kenwood_get_split_vfo_if called
kenwood_get_if called
kenwood_safe_transaction called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(647):kenwood_safe_transaction return(0)
kenwood_get_split_vfo_if: priv->tx_vfo=VFOB
kenwood.c(1483):kenwood_get_split_vfo_if return(0)
kenwood_open: priv->tx_vfo=VFOB
rig.c(2616):rig_set_vfo entered
rig_set_vfo called vfo=VFOA
kenwood_set_vfo called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(1163):kenwood_set_vfo return(0)
kenwood_get_freq called
kenwood_safe_transaction called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(647):kenwood_safe_transaction return(0)
kenwood.c(1760):kenwood_get_freq return(0)
rig.c(2728):rig_set_vfo return(0)
kenwood.c(971):kenwood_open return(0)
rig.c(2753):rig_get_vfo entered
rig.c(2782):rig_get_vfo return(0)
rig.c(1102):rig_open return(0)
rig.c(2328):rig_get_mode entered
kenwood_get_mode called
kenwood_safe_transaction called
kenwood_transaction called
serial.c(642):serial_flush entered
tcflush
serial.c(674):serial_flush return(0)
kenwood.c(577):kenwood_transaction return(0)
kenwood.c(647):kenwood_safe_transaction return(0)
kenwood2rmode called
kenwood.c(659):kenwood2rmode return(8)
rig.c(2455):rig_passband_normal entered
rig_passband_normal: return filter#0, width=2400
rig.c(2475):rig_passband_normal return(2400)
kenwood.c(2395):kenwood_get_mode return(0)
rig.c(1407):set_cache_mode entered
rig.c(1471):set_cache_mode return(0)
rig.c(2434):rig_get_mode return(0)
rig_get_freq(1993) called vfo=currVFO
rig.c(2002) vfo=currVFO, curr_vfo=VFOA
rig.c(2063):rig_get_freq return(0)

**Comment by mdblack98** [comment]
Fixed in FreeDV.
