### ISSUE TITLE
Linux Mint 20.2 compiler error

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#784]
Here is the log of the build attempt:
=====
...all built fine up to this point...
make[4]: Entering directory '/home/mint/fldigi.MXE/mxe/tmp-hamlib-i686-w64-mingw32.static/hamlib-4.3/src'
  CC       rig.lo
  CC       serial.lo
  CC       misc.lo
misc.c: In function 'date_strget':
misc.c:2358:12: warning: implicit declaration of function 'gmtime_r' [-Wimplicit-function-declaration]
     mytm = gmtime_r(&t, &result);

**Comment by N0NB** [comment]
Applied 820e4d4 into Hamlib-4.3.  d6350d1 appears as an exact duplicate so not applied.

**Comment by mdblack98** [comment]
Yup...removed it from the 4.3.1 list.

 

    On Monday, September 13, 2021, 07:33:49 AM CDT, Nate Bargmann ***@***.***> wrote:  
 
 


Applied 820e4d4 into Hamlib-4.3. d6350d1 appears as an exact duplicate so not applied.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
