### ISSUE TITLE
Icom 1A 06 change to read first and set if needed

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#791]
In order to eliminate changing filter every time USB-D is sent we will query first and only set if needed.
Question is...do we re-use the returned filter?  Only if it makes sense when switching modes.

**Comment by mdblack98** [comment]
When USB-D is first set filter 2 will be selected -- after that filters are not touched so may be changed by the user and will stay that way until mode is changed from USB-D to something else and back again and D2 will selected again.
This is more inline with Icom defaults.

**Comment by N0NB** [comment]
Cherry-picked e900b4f and f2c60aa into Hamlib-4.3 branch.
