### ISSUE TITLE
FreeDV Start causes VFOA to be set

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#797]
Regression from older hamlib.
Every time the FreeDV Start button is pressed the rig selects VFOA.
This results from the patch for this issue
https://github.com/Hamlib/Hamlib/issues/745
So we will change to only set VFOA on the 1st rig_open.

**Comment by N0NB** [comment]
If you have a fix/test soon, I can put this in 4.3.1, perhaps.

**Comment by mdblack98** [comment]
Here's the fix...may solve some other problems too.
https://github.com/Hamlib/Hamlib/commit/0f2a92b2de7118f303215cccd1188199711a4b4d



 

    On Monday, September 13, 2021, 04:39:34 PM CDT, Nate Bargmann ***@***.***> wrote:  
 
 


If you have a fix/test soon, I can put this in 4.3.1, perhaps.

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
