### ISSUE TITLE
Automated testing of device backends

### ISSUE THREAD

**Issue by mikaelnousiainen** [Hamlib/Hamlib#80]
(Tried to post this to the mailing list, but it looks like it didn't get through, so I'm reposting here)

Please correct if I'm wrong, but it seems there are currently no tests for individual radio/rotator backends in Hamlib.

I'm seeing this as a big issue, since it is very easy to cause regressions in individual radio commands when refactoring and/or adding new functionality to an existing backend. I've experienced this multiple times during the last year when developing a web-based remote control UI that uses Hamlib to control radios. The basic commands (frequency, mode, VFO) work very well, but in case of controlling a remote station also the Hamlib function and level controls become very important.

I'd really like to take Hamlib "to the next level" in 2019 regarding reliability and completeness of backend command sets by introducing a testing framework for both radio backends and later also for rotator backends.

This framework would mock the normal serial/parallel/USB I/O routines (which is luckily possible because of the excellent I/O abstractions in Hamlib) and do the following:

1. Run a globally defined set of test cases, which would include every single Hamlib command with a predefined set of parameters
2. For each command, the mock routines would
2.1. record the output of all write()-type commands for a particular command
2.2. compare it to a backend-specific byte array for a specific test case
2.3. offer a backend-specific byte array for a specific test case as a response for all read()-type commands
2.4. check the expected return value of the Hamlib command executed

Every test case would naturally need a unique identifier so that the global test framework could search for valid test cases for each backend. Backend would need to register a data structure containing the test case expectations for the command output and return value and the device response to be offered to the backend.

In order to develop and to extend the set of test cases, a missing test case would not indicate a failure, but we could generate a HTML matrix similar to the rig command support matrix containing the test cases executed and present for each backend.

What I'd like to accomplish with this setup is:

A) When making changes to Hamlib code, we could verify that each and every Hamlib command still outputs the same device-specific command for a specific backend and that the backend interprets device responses, including errors, correctly. There have been cases where simple changes to, for example, fix compiler warnings have resulted in broken code (I saw one with IC-7300 backend last year).

B) When adding new functionality it would become more apparent when to branch code for a new model: e.g. Elecraft KX3/K3/K3s have many similar commands, but are not 100% compatible -- yet they share the backend code. There should always be a good reason to change the expected output of a test, so nothing would go unnoticed.

Adding test data for all backends is a huge task and will need a lot of effort from the whole Hamlib developer community, but I think automated testing is the _only_ way forward if we wish to keep Hamlib usable and maintainable when we are making breaking changes (like now for 4.0 release). In addition, the list of supported hardware keeps on growing and radios are becoming more complex with wider sets of features, which certainly does not make Hamlib development easier :)

Please share your thoughts about this kind of effort. If you feel this change would be welcome, I can continue by posting more detailed design in GitHub.

73,
Mikael OH3BHX

**Comment by mdblack98** [comment]
This is an almost impossible task.  Comprehensive testing is complicated enough for one rig let alone all of them.  A lot of problems are timing related which wouldn't show up in such testing.
Nice thought but not likely to ever be implemented.
