### ISSUE TITLE
TS-450 slow PTT

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#845]
Hi Mike,
I have been seeing the same slow changes between TX and RX with the TS-450S since the recent fix for split. The rig beeps at each CAT command and there is a long burst of beeps that I never had previously.
I will help with logs if required using a build from master.

**Comment by barjac** [comment]
Hi Mike,
Your changes in 746ba96 seem to have fixed the problem.

I rebuilt hamlib at the above commit and rebuilt wsjtx against it. The RX/TX changes are no longer bombarding me with morse code, and response from rig is much faster. :)

[rigctl_746ba96_1.log](https://github.com/Hamlib/Hamlib/files/7447795/rigctl_746ba96_1.log)

The above is from starting rigctld, starting wsjtx, call CQ, briefly and abort it, tune and halt it, then change band and stop wsjtx and rigctld.
Many thanks,
Barry
G4MKT
