### ISSUE TITLE
IC-910 not changing modes

### ISSUE THREAD

**Issue by mjswiatk** [Hamlib/Hamlib#871]
When using GPredict with hamlib, the IC-910 does not change modes (USB, LSB, FM) when using the radio control feature. (This menu is in the upper right corner of main window.)  Is this a hamlib issue or a GPredict issue?  I am using hamlib-w64-4.3.1.exe

**Comment by mdblack98** [comment]
gpredict does not set rig mode...not a hamlib problem.

**Comment by mjswiatk** [comment]
thanks for reviewing.


Mike
