### ISSUE TITLE
Find a workaround to get Icom VFO state to properly support Icom transceive data

### ISSUE THREAD

**Issue by mikaelnousiainen** [Hamlib/Hamlib#896]
Follow-up task for features initially implemented in #892.

Icom transceive data doesn't contain any information about the current VFO, so it is not possible to use it to update Hamlib cache state on its own.

However, we could probably find some clever way to use the 0x25 CI-V command to figure out which VFO is currently active.

It seems that at least IC-7300 outputs a mode change transceive message when changing VFO (even if the mode doesn't change), so that could be potentially used as a trigger to execute the logic to figure out the current VFO.

**Comment by mdblack98** [comment]
Active VFO determination is done during startup for Icom rigs now.
But it takes way too many commands and causes VFO flashing so we cannot have a standard "get_vfo" call without causing havoc.
Icoms can now run with VFOB/Sub as the primary if they want now.  Just have to have it selected at startup.
