### ISSUE TITLE
Yaesu Band select

### ISSUE THREAD

**Issue by Johnny-Sierra** [Hamlib/Hamlib#919]
Implement Band select command in Yaesu newcat backend. It is useful beacuse it allows to use the Yaesu stack function.
I suggest to add this command as level in the set_level function.

Command format is:
BS P1P1;

Where P1P1 is integer

Yaesu FT991 example:
00 - 1.8 MHz
01 - 3.5 MHz
02 - 5
03 - 7
04 - 10
05 - 14
06 - 18
07 - 21
08 - 24.5
09 - 28
10 - 50
11 - GEN
12 - MW
13 - not used
14 - AIR
15 - 144 MHz
16 - 430

**Comment by mdblack98** [comment]
Please test the new RIG_LEVEL_BAND_SELECT

**Comment by jleh** [comment]
Tested this with FT991A. All bands & stacks seems to be working, but if an unknown band value is provided, the rig always sets band to 0 (160 m).

**Comment by mdblack98** [comment]
Should give an error now.
Mike 

    On Tuesday, February 1, 2022, 11:27:30 AM CST, Juuso Lehtinen ***@***.***> wrote:  
 
 


Tested this with FT991A. All bands & stacks seems to be working, but if an unknown band value is provided, the rig always sets band to 0 (160 m).

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Johnny-Sierra** [comment]
Sorry, I'm not able to test it with #f08c7d7e
My software doesn't connect to the com port with this snapshot.

**Comment by mdblack98** [comment]
Get the current version and try again

**Comment by mdblack98** [comment]
Have you tried the latest version now?

**Comment by Johnny-Sierra** [comment]
Hi Mike, finally I got my software running with snapshot #b9d3de3c

These are the results with Yaesu FT-991A
0: 160m, OK
1: error -1, NOK
2: select band 80m, NOK
3: error -1, NOK
4: select band 60m, NOK
5: error -1, NOK
6: error -1, NOK
7: error -1, NOK
8: select band 40m, NOK
9: error -1, NOK
10: error -1, NOK
11: error -1, NOK
12: error -1, NOK

Something is wrong, this is my piece of code, maybe I'm missing something:
retvalue.i = band;
retcode = rig_set_level(my_rig, RIG_VFO_CURR, RIG_LEVEL_BAND_SELECT, retvalue);

**Comment by mdblack98** [comment]
Actually I had the band indexed via an enumerated type with bit shifts.
But it makes more sense for Yaesu rigs to just follow the numbering in the CAT manual.
So I changed them to match.
What will work for all rigs though when implemented for other rigs is to use the band_t enumerations since the band indexes probably won't match.  And if these bands ever get extended or changed the enumerations will still work.
typedef enum { // numbers here reflect the Yaesu values
    RIG_BAND_160M = 0,      /*!< \c 160M */
    RIG_BAND_80M  = 1,      /*!< \c 80M */
    RIG_BAND_60M  = 2,      /*!< \c 60M */
    RIG_BAND_40M  = 3,      /*!< \c 40M */
    RIG_BAND_30M  = 4,      /*!< \c 30M */
    RIG_BAND_20M  = 5,      /*!< \c 20M */
    RIG_BAND_17M  = 6,      /*!< \c 17M */
    RIG_BAND_15M  = 7,      /*!< \c 15M */
    RIG_BAND_12M  = 8,      /*!< \c 12M */
    RIG_BAND_10M  = 9,      /*!< \c 10M */
    RIG_BAND_6M   = 10,     /*!< \c 6M */
    RIG_BAND_GEN = 11,      /*!< \c 60M */
    RIG_BAND_MW  = 12,      /*!< \c Medium Wave */
    RIG_BAND_UNUSED  = 13,  /*!< \c Medium Wave */
    RIG_BAND_AIR = 14,      /*!< \c Air band */
    RIG_BAND_144MHZ = 15,   /*!< \c 144MHz */
    RIG_BAND_430MHZ = 16,   /*!< \c 430MHz */
} hamlib_band_t;

**Comment by Johnny-Sierra** [comment]
Ah, ok. Sorry my mistake.
Changed my code using the enum type, now no problem with FT991.
It should work also with other Yaesu radios.
