### ISSUE TITLE
Expand data types accepted by XML-RPC

### ISSUE THREAD

**Issue by AG7GN** [Hamlib/Hamlib#945]
I'm writing my own Flrig-like application that can communicate with Hamlib (using the Flrig rig) and Fldigi via XML-RPC. I'm writing it in Python using the [xmlrpc.server](https://docs.python.org/3/library/xmlrpc.server.html) module. This module doesn't support the `nil` or `i4` data types, but it [does support](https://docs.python.org/3/library/xmlrpc.client.html) `int` and `string`.

I've found that by changing this line in Hamlib's `rigs/dummy/flrig.c`:

```
    if (streq(p, "i4") || streq(p, "double"))
```
to:
```
    if (streq(p, "i4") || streq(p, "double") || streq(p, "int") || streq(p, "string"))
```
that my application works well with Hamlib. It already works well with Fldigi without modifications to Fldigi.

Would you consider making this change in your source code?

**Comment by mdblack98** [comment]
Done.
Mike W9MDB

 

    On Saturday, January 29, 2022, 08:28:49 PM CST, AG7GN ***@***.***> wrote:  
 
 


I'm writing my own Flrig-like application that can communicate with Hamlib (using the Flrig rig) and Fldigi via XML-RPC. I'm writing it in Python using the xmlrpc.server module. This module doesn't support the nil or i4 data types, but it does support int and string.

I've found that by changing this line in Hamlib's rigs/dummy/flrig.c:
    if (streq(p, "i4") || streq(p, "double"))

to:
    if (streq(p, "i4") || streq(p, "double") || streq(p, "int") || streq(p, "string"))

that my application works well with Hamlib. It already works well with Fldigi without modifications to Fldigi.

Would you consider making this change in your source code?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AG7GN** [comment]
Thank you.
