### ISSUE TITLE
Connection is unstable

### ISSUE THREAD

**Issue by Supermagnum** [Hamlib/Hamlib#982]
Hello, for some reason I got a lot of these:
Hamlib error: IO error
port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory
iofunc.c(81):port_open return(-6)
rig.c(800):rig_open return(-6) while opening connection to rig

Timestamp: 2022-03-08T09:00:08.838Z

Hamlib error: IO error
port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory
iofunc.c(81):port_open return(-6)
rig.c(800):rig_open return(-6) while opening connection to rig

Timestamp: 2022-03-08T09:05:52.387Z

Hamlib error: IO error
port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory
iofunc.c(81):port_open return(-6)
rig.c(800):rig_open return(-6) while opening connection to rig

Timestamp: 2022-03-08T09:07:11.743Z

It seems that the connection for some reason goes up and down, 
I then reconfigure the radio with exact the same settings in wsjtx, then it works for a while and the same happens.
It is not related to any RFI because it happens even if I am only listening.

The rig is a FT-991. I am running Linux mint.
Could this be a bad USB cable ?

**Comment by mdblack98** [comment]
You can still have RFI even if you aren't transmitting but I agree that it's unlikely as it would be a much lower level.  You can get 60Hz for example from wall warts, LED lights, grow lights, power company transformers, and such.If there's "no such file" then the device has disappeared and if you run "dmesg" you'll probably see the USB messages on the device disappearing and reappearing.
I would run overnight with WSJT-X not running and see if the USB cable still disconnects (in dmesg).
Then I would try another USB cable.
Mike W9MDB


 

    On Tuesday, March 8, 2022, 03:08:58 AM CST, Supermagnum ***@***.***> wrote:  
 
 


Hello, for some reason I got a lot of these:
Hamlib error: IO error
port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory
iofunc.c(81):port_open return(-6)
rig.c(800):rig_open return(-6) while opening connection to rig

Timestamp: 2022-03-08T09:00:08.838Z

Hamlib error: IO error
port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory
iofunc.c(81):port_open return(-6)
rig.c(800):rig_open return(-6) while opening connection to rig

Timestamp: 2022-03-08T09:05:52.387Z

Hamlib error: IO error
port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory
iofunc.c(81):port_open return(-6)
rig.c(800):rig_open return(-6) while opening connection to rig

Timestamp: 2022-03-08T09:07:11.743Z

It seems that the connection for some reason goes up and down,
I then reconfigure the radio with exact the same settings in wsjtx, then it works for a while and the same happens.
It is not related to any RFI because it happens even if I am only listening.

The rig is a FT-991. I am running Linux mint.
Could this be a bad USB cable ?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Supermagnum** [comment]
> You can still have RFI even if you aren't transmitting but I agree that it's unlikely as it would be a much lower level.  You can get 60Hz for example from wall warts, LED lights, grow lights, power company transformers, and such.If there's "no such file" then the device has disappeared and if you run "dmesg" you'll probably see the USB messages on the device disappearing and reappearing. I would run overnight with WSJT-X not running and see if the USB cable still disconnects (in dmesg). Then I would try another USB cable. Mike W9MDB On Tuesday, March 8, 2022, 03:08:58 AM CST, Supermagnum ***@***.***> wrote: Hello, for some reason I got a lot of these: Hamlib error: IO error port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory iofunc.c(81):port_open return(-6) rig.c(800):rig_open return(-6) while opening connection to rig Timestamp: 2022-03-08T09:00:08.838Z Hamlib error: IO error port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory iofunc.c(81):port_open return(-6) rig.c(800):rig_open return(-6) while opening connection to rig Timestamp: 2022-03-08T09:05:52.387Z Hamlib error: IO error port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory iofunc.c(81):port_open return(-6) rig.c(800):rig_open return(-6) while opening connection to rig Timestamp: 2022-03-08T09:07:11.743Z It seems that the connection for some reason goes up and down, I then reconfigure the radio with exact the same settings in wsjtx, then it works for a while and the same happens. It is not related to any RFI because it happens even if I am only listening. The rig is a FT-991. I am running Linux mint. Could this be a bad USB cable ? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

It looks like the issue is related to wsjtx-z, because it doesn't happen with the normal newest wsjt and Hamlib 4.4

**Comment by Supermagnum** [comment]
> You can still have RFI even if you aren't transmitting but I agree that it's unlikely as it would be a much lower level.  You can get 60Hz for example from wall warts, LED lights, grow lights, power company transformers, and such.If there's "no such file" then the device has disappeared and if you run "dmesg" you'll probably see the USB messages on the device disappearing and reappearing. I would run overnight with WSJT-X not running and see if the USB cable still disconnects (in dmesg). Then I would try another USB cable. Mike W9MDB On Tuesday, March 8, 2022, 03:08:58 AM CST, Supermagnum ***@***.***> wrote: Hello, for some reason I got a lot of these: Hamlib error: IO error port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory iofunc.c(81):port_open return(-6) rig.c(800):rig_open return(-6) while opening connection to rig Timestamp: 2022-03-08T09:00:08.838Z Hamlib error: IO error port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory iofunc.c(81):port_open return(-6) rig.c(800):rig_open return(-6) while opening connection to rig Timestamp: 2022-03-08T09:05:52.387Z Hamlib error: IO error port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory iofunc.c(81):port_open return(-6) rig.c(800):rig_open return(-6) while opening connection to rig Timestamp: 2022-03-08T09:07:11.743Z It seems that the connection for some reason goes up and down, I then reconfigure the radio with exact the same settings in wsjtx, then it works for a while and the same happens. It is not related to any RFI because it happens even if I am only listening. The rig is a FT-991. I am running Linux mint. Could this be a bad USB cable ? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Here is the relevant log from dmesg, it does reset itself. I will try to get hold of a new USB cable.
Hopefully that fixes the issue.

[    8.206915] usb 1-6: USB disconnect, device number 4
[    8.206918] usb 1-6.1: USB disconnect, device number 5
[    8.207122] cp210x ttyUSB0: cp210x converter now disconnected from ttyUSB0
[    8.207144] cp210x 1-6.1:1.0: device disconnected
[    8.207282] cp210x ttyUSB1: cp210x converter now disconnected from ttyUSB1
[    8.207300] cp210x 1-6.1:1.1: device disconnected
[    8.212754] usb 1-6.2: USB disconnect, device number 6
[    8.256813] EDAC amd64: Node 0: DRAM ECC disabled.
[    8.256816] EDAC amd64: ECC disabled in the BIOS or no ECC capability, module will not load.
                Either enable ECC checking or force module loading by setting 'ecc_enable_override'.
                (Note that use of the override may cause unknown side effects.)
[    8.258673] kvm: disabled by bios
[    8.354510] EDAC amd64: Node 0: DRAM ECC disabled.
[    8.354513] EDAC amd64: ECC disabled in the BIOS or no ECC capability, module will not load.
                Either enable ECC checking or force module loading by setting 'ecc_enable_override'.
                (Note that use of the override may cause unknown side effects.)
[    8.354568] kvm: disabled by bios
[    8.454130] EDAC amd64: Node 0: DRAM ECC disabled.
[    8.454132] EDAC amd64: ECC disabled in the BIOS or no ECC capability, module will not load.
                Either enable ECC checking or force module loading by setting 'ecc_enable_override'.
                (Note that use of the override may cause unknown side effects.)
[    8.563749] usb 1-6: new high-speed USB device number 7 using xhci_hcd
[    8.787762] usb 1-6: New USB device found, idVendor=0424, idProduct=2512, bcdDevice= b.b3
[    8.787765] usb 1-6: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    8.794798] hub 1-6:1.0: USB hub found
[    8.797747] hub 1-6:1.0: 2 ports detected
[    9.119906] usb 1-6.1: new full-speed USB device number 8 using xhci_hcd
[    9.380283] igb 0000:04:00.0 enp4s0: igb: enp4s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
[    9.447801] usb 1-6.1: New USB device found, idVendor=10c4, idProduct=ea70, bcdDevice= 1.00
[    9.447803] usb 1-6.1: New USB device strings: Mfr=1, Product=2, SerialNumber=5
[    9.447804] usb 1-6.1: Product: CP2105 Dual USB to UART Bridge Controller
[    9.447805] usb 1-6.1: Manufacturer: Silicon Labs
[    9.447806] usb 1-6.1: SerialNumber: AH057M5I150145
[    9.474860] cp210x 1-6.1:1.0: cp210x converter detected
[    9.492814] gpio gpiochip2: (cp210x): tried to insert a GPIO chip with zero lines
[    9.492819] gpiochip_add_data_with_key: GPIOs 0..-1 (cp210x) failed to register, -22
[    9.492823] cp210x 1-6.1:1.0: GPIO initialisation failed: -22
[    9.512883] usb 1-6.1: cp210x converter now attached to ttyUSB0
[    9.518844] cp210x 1-6.1:1.1: cp210x converter detected
[    9.536815] gpio gpiochip2: (cp210x): tried to insert a GPIO chip with zero lines
[    9.536820] gpiochip_add_data_with_key: GPIOs 0..-1 (cp210x) failed to register, -22
[    9.536823] cp210x 1-6.1:1.1: GPIO initialisation failed: -22
[    9.556878] usb 1-6.1: cp210x converter now attached to ttyUSB1
[    9.603984] IPv6: ADDRCONF(NETDEV_CHANGE): enp4s0: link becomes ready
[    9.643732] usb 1-6.2: new full-speed USB device number 9 using xhci_hcd
[   10.257935] usb 1-6.2: New USB device found, idVendor=08bb, idProduct=29b3, bcdDevice= 1.00
[   10.257939] usb 1-6.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   10.257941] usb 1-6.2: Product: USB Audio CODEC 
[   10.257943] usb 1-6.2: Manufacturer: Burr-Brown from TI              
[   10.617199] input: Burr-Brown from TI               USB Audio CODEC  as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-6/1-6.2/1-6.2:1.3/0003:08BB:29B3.0005/input/input22
[   10.675981] hid-generic 0003:08BB:29B3.0005: input,hidraw3: USB HID v1.00 Device [Burr-Brown from TI               USB Audio CODEC ] on usb-0000:02:00.0-6.2/input3
[  261.681719] usb 1-6: USB disconnect, device number 7
[  261.681723] usb 1-6.1: USB disconnect, device number 8
[  261.682183] cp210x ttyUSB0: cp210x converter now disconnected from ttyUSB0
[  261.682205] cp210x 1-6.1:1.0: device disconnected
[  261.682345] cp210x ttyUSB1: cp210x converter now disconnected from ttyUSB1
[  261.682363] cp210x 1-6.1:1.1: device disconnected
[  261.684703] usb 1-6.2: cannot submit urb (err = -19)
[  261.687945] usb 1-6.2: USB disconnect, device number 9
[  262.024770] usb 1-6: new high-speed USB device number 10 using xhci_hcd
[  262.249337] usb 1-6: New USB device found, idVendor=0424, idProduct=2512, bcdDevice= b.b3
[  262.249340] usb 1-6: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[  262.256226] hub 1-6:1.0: USB hub found
[  262.259179] hub 1-6:1.0: 2 ports detected
[  262.580908] usb 1-6.1: new full-speed USB device number 11 using xhci_hcd
[  262.904489] usb 1-6.1: New USB device found, idVendor=10c4, idProduct=ea70, bcdDevice= 1.00
[  262.904492] usb 1-6.1: New USB device strings: Mfr=1, Product=2, SerialNumber=5
[  262.904494] usb 1-6.1: Product: CP2105 Dual USB to UART Bridge Controller
[  262.904496] usb 1-6.1: Manufacturer: Silicon Labs
[  262.904498] usb 1-6.1: SerialNumber: AH057M5I150145
[  262.933584] cp210x 1-6.1:1.0: cp210x converter detected
[  262.951417] gpio gpiochip2: (cp210x): tried to insert a GPIO chip with zero lines
[  262.951422] gpiochip_add_data_with_key: GPIOs 0..-1 (cp210x) failed to register, -22
[  262.951425] cp210x 1-6.1:1.0: GPIO initialisation failed: -22
[  262.971365] usb 1-6.1: cp210x converter now attached to ttyUSB0
[  262.977296] cp210x 1-6.1:1.1: cp210x converter detected
[  262.995278] gpio gpiochip2: (cp210x): tried to insert a GPIO chip with zero lines
[  262.995284] gpiochip_add_data_with_key: GPIOs 0..-1 (cp210x) failed to register, -22
[  262.995287] cp210x 1-6.1:1.1: GPIO initialisation failed: -22
[  263.015361] usb 1-6.1: cp210x converter now attached to ttyUSB1
[  263.104761] usb 1-6.2: new full-speed USB device number 12 using xhci_hcd
[  263.723336] usb 1-6.2: New USB device found, idVendor=08bb, idProduct=29b3, bcdDevice= 1.00
[  263.723340] usb 1-6.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  263.723343] usb 1-6.2: Product: USB Audio CODEC 
[  263.723344] usb 1-6.2: Manufacturer: Burr-Brown from TI              
[  264.082646] input: Burr-Brown from TI               USB Audio CODEC  as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-6/1-6.2/1-6.2:1.3/0003:08BB:29B3.0006/input/input23
[  264.140943] hid-generic 0003:08BB:29B3.0006: input,hidraw3: USB HID v1.00 Device [Burr-Brown from TI               USB Audio CODEC ] on usb-0000:02:00.0-6.2/input3
[  798.323464] usb 1-6: USB disconnect, device number 10
[  798.323468] usb 1-6.1: USB disconnect, device number 11
[  798.323900] cp210x ttyUSB0: failed set request 0x12 status: -19
[  798.323905] cp210x ttyUSB0: failed set request 0x0 status: -19
[  798.324032] cp210x ttyUSB0: cp210x converter now disconnected from ttyUSB0
[  798.324048] cp210x 1-6.1:1.0: device disconnected
[  798.324191] cp210x ttyUSB1: cp210x converter now disconnected from ttyUSB1
[  798.324210] cp210x 1-6.1:1.1: device disconnected
[  798.327228] usb 1-6.2: cannot submit urb (err = -19)
[  798.329600] usb 1-6.2: USB disconnect, device number 12
[  798.687058] usb 1-6: new high-speed USB device number 13 using xhci_hcd
[  798.911711] usb 1-6: New USB device found, idVendor=0424, idProduct=2512, bcdDevice= b.b3
[  798.911715] usb 1-6: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[  798.918750] hub 1-6:1.0: USB hub found
[  798.921695] hub 1-6:1.0: 2 ports detected
[  799.243201] usb 1-6.1: new full-speed USB device number 14 using xhci_hcd
[  799.566795] usb 1-6.1: New USB device found, idVendor=10c4, idProduct=ea70, bcdDevice= 1.00
[  799.566799] usb 1-6.1: New USB device strings: Mfr=1, Product=2, SerialNumber=5
[  799.566801] usb 1-6.1: Product: CP2105 Dual USB to UART Bridge Controller
[  799.566803] usb 1-6.1: Manufacturer: Silicon Labs
[  799.566805] usb 1-6.1: SerialNumber: AH057M5I150145
[  799.594850] cp210x 1-6.1:1.0: cp210x converter detected
[  799.612795] gpio gpiochip2: (cp210x): tried to insert a GPIO chip with zero lines
[  799.612801] gpiochip_add_data_with_key: GPIOs 0..-1 (cp210x) failed to register, -22
[  799.612805] cp210x 1-6.1:1.0: GPIO initialisation failed: -22
[  799.632880] usb 1-6.1: cp210x converter now attached to ttyUSB1
[  799.638851] cp210x 1-6.1:1.1: cp210x converter detected
[  799.656812] gpio gpiochip2: (cp210x): tried to insert a GPIO chip with zero lines
[  799.656818] gpiochip_add_data_with_key: GPIOs 0..-1 (cp210x) failed to register, -22
[  799.656821] cp210x 1-6.1:1.1: GPIO initialisation failed: -22    
[  799.676864] usb 1-6.1: cp210x converter now attached to ttyUSB2
[  799.767078] usb 1-6.2: new full-speed USB device number 15 using xhci_hcd
[  800.384899] usb 1-6.2: New USB device found, idVendor=08bb, idProduct=29b3, bcdDevice= 1.00
[  800.384904] usb 1-6.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  800.384906] usb 1-6.2: Product: USB Audio CODEC 
[  800.384908] usb 1-6.2: Manufacturer: Burr-Brown from TI              
[  800.745185] input: Burr-Brown from TI               USB Audio CODEC  as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-6/1-6.2/1-6.2:1.3/0003:08BB:29B3.0007/input/input24
[  800.803239] hid-generic 0003:08BB:29B3.0007: input,hidraw3: USB HID v1.00 Device [Burr-Brown from TI               USB Audio CODEC ] on usb-0000:02:00.0-6.2/input3

**Comment by Supermagnum** [comment]
closed due to bad usb cable
