### ISSUE TITLE
Add support for AOR AR-DV10

### ISSUE THREAD

**Issue by majkrzak** [Hamlib/Hamlib#984]
Hamlib is missing support of some AOR receivers, like mentioned AR-DV10. Briefly looking to the [code](https://github.com/Hamlib/Hamlib/tree/master/rigs/aor) and the [command list summary](http://www.aorja.com/support/manuals/AR-DV10_AND_AR-DV1_COMMAND_LIST_SUMMARY.pdf) shows that it is more or less the same as other AOR devices.

I think I can handle this with little help or guidance.

**Comment by mdblack98** [comment]
All patches are welcome.
